// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"agent/internal/model"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ServiceMock implements mm_transport.Service
type ServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteTask          func(ctx context.Context, requestID string, user *model.User) (err error)
	funcDeleteTaskOrigin    string
	inspectFuncDeleteTask   func(ctx context.Context, requestID string, user *model.User)
	afterDeleteTaskCounter  uint64
	beforeDeleteTaskCounter uint64
	DeleteTaskMock          mServiceMockDeleteTask

	funcUpsertUser          func(ctx context.Context, requestID string, user *model.User) (err error)
	funcUpsertUserOrigin    string
	inspectFuncUpsertUser   func(ctx context.Context, requestID string, user *model.User)
	afterUpsertUserCounter  uint64
	beforeUpsertUserCounter uint64
	UpsertUserMock          mServiceMockUpsertUser
}

// NewServiceMock returns a mock for mm_transport.Service
func NewServiceMock(t minimock.Tester) *ServiceMock {
	m := &ServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteTaskMock = mServiceMockDeleteTask{mock: m}
	m.DeleteTaskMock.callArgs = []*ServiceMockDeleteTaskParams{}

	m.UpsertUserMock = mServiceMockUpsertUser{mock: m}
	m.UpsertUserMock.callArgs = []*ServiceMockUpsertUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mServiceMockDeleteTask struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockDeleteTaskExpectation
	expectations       []*ServiceMockDeleteTaskExpectation

	callArgs []*ServiceMockDeleteTaskParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockDeleteTaskExpectation specifies expectation struct of the Service.DeleteTask
type ServiceMockDeleteTaskExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockDeleteTaskParams
	paramPtrs          *ServiceMockDeleteTaskParamPtrs
	expectationOrigins ServiceMockDeleteTaskExpectationOrigins
	results            *ServiceMockDeleteTaskResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockDeleteTaskParams contains parameters of the Service.DeleteTask
type ServiceMockDeleteTaskParams struct {
	ctx       context.Context
	requestID string
	user      *model.User
}

// ServiceMockDeleteTaskParamPtrs contains pointers to parameters of the Service.DeleteTask
type ServiceMockDeleteTaskParamPtrs struct {
	ctx       *context.Context
	requestID *string
	user      **model.User
}

// ServiceMockDeleteTaskResults contains results of the Service.DeleteTask
type ServiceMockDeleteTaskResults struct {
	err error
}

// ServiceMockDeleteTaskOrigins contains origins of expectations of the Service.DeleteTask
type ServiceMockDeleteTaskExpectationOrigins struct {
	origin          string
	originCtx       string
	originRequestID string
	originUser      string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteTask *mServiceMockDeleteTask) Optional() *mServiceMockDeleteTask {
	mmDeleteTask.optional = true
	return mmDeleteTask
}

// Expect sets up expected params for Service.DeleteTask
func (mmDeleteTask *mServiceMockDeleteTask) Expect(ctx context.Context, requestID string, user *model.User) *mServiceMockDeleteTask {
	if mmDeleteTask.mock.funcDeleteTask != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Set")
	}

	if mmDeleteTask.defaultExpectation == nil {
		mmDeleteTask.defaultExpectation = &ServiceMockDeleteTaskExpectation{}
	}

	if mmDeleteTask.defaultExpectation.paramPtrs != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by ExpectParams functions")
	}

	mmDeleteTask.defaultExpectation.params = &ServiceMockDeleteTaskParams{ctx, requestID, user}
	mmDeleteTask.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteTask.expectations {
		if minimock.Equal(e.params, mmDeleteTask.defaultExpectation.params) {
			mmDeleteTask.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteTask.defaultExpectation.params)
		}
	}

	return mmDeleteTask
}

// ExpectCtxParam1 sets up expected param ctx for Service.DeleteTask
func (mmDeleteTask *mServiceMockDeleteTask) ExpectCtxParam1(ctx context.Context) *mServiceMockDeleteTask {
	if mmDeleteTask.mock.funcDeleteTask != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Set")
	}

	if mmDeleteTask.defaultExpectation == nil {
		mmDeleteTask.defaultExpectation = &ServiceMockDeleteTaskExpectation{}
	}

	if mmDeleteTask.defaultExpectation.params != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Expect")
	}

	if mmDeleteTask.defaultExpectation.paramPtrs == nil {
		mmDeleteTask.defaultExpectation.paramPtrs = &ServiceMockDeleteTaskParamPtrs{}
	}
	mmDeleteTask.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteTask.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteTask
}

// ExpectRequestIDParam2 sets up expected param requestID for Service.DeleteTask
func (mmDeleteTask *mServiceMockDeleteTask) ExpectRequestIDParam2(requestID string) *mServiceMockDeleteTask {
	if mmDeleteTask.mock.funcDeleteTask != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Set")
	}

	if mmDeleteTask.defaultExpectation == nil {
		mmDeleteTask.defaultExpectation = &ServiceMockDeleteTaskExpectation{}
	}

	if mmDeleteTask.defaultExpectation.params != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Expect")
	}

	if mmDeleteTask.defaultExpectation.paramPtrs == nil {
		mmDeleteTask.defaultExpectation.paramPtrs = &ServiceMockDeleteTaskParamPtrs{}
	}
	mmDeleteTask.defaultExpectation.paramPtrs.requestID = &requestID
	mmDeleteTask.defaultExpectation.expectationOrigins.originRequestID = minimock.CallerInfo(1)

	return mmDeleteTask
}

// ExpectUserParam3 sets up expected param user for Service.DeleteTask
func (mmDeleteTask *mServiceMockDeleteTask) ExpectUserParam3(user *model.User) *mServiceMockDeleteTask {
	if mmDeleteTask.mock.funcDeleteTask != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Set")
	}

	if mmDeleteTask.defaultExpectation == nil {
		mmDeleteTask.defaultExpectation = &ServiceMockDeleteTaskExpectation{}
	}

	if mmDeleteTask.defaultExpectation.params != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Expect")
	}

	if mmDeleteTask.defaultExpectation.paramPtrs == nil {
		mmDeleteTask.defaultExpectation.paramPtrs = &ServiceMockDeleteTaskParamPtrs{}
	}
	mmDeleteTask.defaultExpectation.paramPtrs.user = &user
	mmDeleteTask.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmDeleteTask
}

// Inspect accepts an inspector function that has same arguments as the Service.DeleteTask
func (mmDeleteTask *mServiceMockDeleteTask) Inspect(f func(ctx context.Context, requestID string, user *model.User)) *mServiceMockDeleteTask {
	if mmDeleteTask.mock.inspectFuncDeleteTask != nil {
		mmDeleteTask.mock.t.Fatalf("Inspect function is already set for ServiceMock.DeleteTask")
	}

	mmDeleteTask.mock.inspectFuncDeleteTask = f

	return mmDeleteTask
}

// Return sets up results that will be returned by Service.DeleteTask
func (mmDeleteTask *mServiceMockDeleteTask) Return(err error) *ServiceMock {
	if mmDeleteTask.mock.funcDeleteTask != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Set")
	}

	if mmDeleteTask.defaultExpectation == nil {
		mmDeleteTask.defaultExpectation = &ServiceMockDeleteTaskExpectation{mock: mmDeleteTask.mock}
	}
	mmDeleteTask.defaultExpectation.results = &ServiceMockDeleteTaskResults{err}
	mmDeleteTask.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteTask.mock
}

// Set uses given function f to mock the Service.DeleteTask method
func (mmDeleteTask *mServiceMockDeleteTask) Set(f func(ctx context.Context, requestID string, user *model.User) (err error)) *ServiceMock {
	if mmDeleteTask.defaultExpectation != nil {
		mmDeleteTask.mock.t.Fatalf("Default expectation is already set for the Service.DeleteTask method")
	}

	if len(mmDeleteTask.expectations) > 0 {
		mmDeleteTask.mock.t.Fatalf("Some expectations are already set for the Service.DeleteTask method")
	}

	mmDeleteTask.mock.funcDeleteTask = f
	mmDeleteTask.mock.funcDeleteTaskOrigin = minimock.CallerInfo(1)
	return mmDeleteTask.mock
}

// When sets expectation for the Service.DeleteTask which will trigger the result defined by the following
// Then helper
func (mmDeleteTask *mServiceMockDeleteTask) When(ctx context.Context, requestID string, user *model.User) *ServiceMockDeleteTaskExpectation {
	if mmDeleteTask.mock.funcDeleteTask != nil {
		mmDeleteTask.mock.t.Fatalf("ServiceMock.DeleteTask mock is already set by Set")
	}

	expectation := &ServiceMockDeleteTaskExpectation{
		mock:               mmDeleteTask.mock,
		params:             &ServiceMockDeleteTaskParams{ctx, requestID, user},
		expectationOrigins: ServiceMockDeleteTaskExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteTask.expectations = append(mmDeleteTask.expectations, expectation)
	return expectation
}

// Then sets up Service.DeleteTask return parameters for the expectation previously defined by the When method
func (e *ServiceMockDeleteTaskExpectation) Then(err error) *ServiceMock {
	e.results = &ServiceMockDeleteTaskResults{err}
	return e.mock
}

// Times sets number of times Service.DeleteTask should be invoked
func (mmDeleteTask *mServiceMockDeleteTask) Times(n uint64) *mServiceMockDeleteTask {
	if n == 0 {
		mmDeleteTask.mock.t.Fatalf("Times of ServiceMock.DeleteTask mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteTask.expectedInvocations, n)
	mmDeleteTask.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteTask
}

func (mmDeleteTask *mServiceMockDeleteTask) invocationsDone() bool {
	if len(mmDeleteTask.expectations) == 0 && mmDeleteTask.defaultExpectation == nil && mmDeleteTask.mock.funcDeleteTask == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteTask.mock.afterDeleteTaskCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteTask.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteTask implements mm_transport.Service
func (mmDeleteTask *ServiceMock) DeleteTask(ctx context.Context, requestID string, user *model.User) (err error) {
	mm_atomic.AddUint64(&mmDeleteTask.beforeDeleteTaskCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteTask.afterDeleteTaskCounter, 1)

	mmDeleteTask.t.Helper()

	if mmDeleteTask.inspectFuncDeleteTask != nil {
		mmDeleteTask.inspectFuncDeleteTask(ctx, requestID, user)
	}

	mm_params := ServiceMockDeleteTaskParams{ctx, requestID, user}

	// Record call args
	mmDeleteTask.DeleteTaskMock.mutex.Lock()
	mmDeleteTask.DeleteTaskMock.callArgs = append(mmDeleteTask.DeleteTaskMock.callArgs, &mm_params)
	mmDeleteTask.DeleteTaskMock.mutex.Unlock()

	for _, e := range mmDeleteTask.DeleteTaskMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteTask.DeleteTaskMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteTask.DeleteTaskMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteTask.DeleteTaskMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteTask.DeleteTaskMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockDeleteTaskParams{ctx, requestID, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteTask.t.Errorf("ServiceMock.DeleteTask got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteTask.DeleteTaskMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.requestID != nil && !minimock.Equal(*mm_want_ptrs.requestID, mm_got.requestID) {
				mmDeleteTask.t.Errorf("ServiceMock.DeleteTask got unexpected parameter requestID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteTask.DeleteTaskMock.defaultExpectation.expectationOrigins.originRequestID, *mm_want_ptrs.requestID, mm_got.requestID, minimock.Diff(*mm_want_ptrs.requestID, mm_got.requestID))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmDeleteTask.t.Errorf("ServiceMock.DeleteTask got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteTask.DeleteTaskMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteTask.t.Errorf("ServiceMock.DeleteTask got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteTask.DeleteTaskMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteTask.DeleteTaskMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteTask.t.Fatal("No results are set for the ServiceMock.DeleteTask")
		}
		return (*mm_results).err
	}
	if mmDeleteTask.funcDeleteTask != nil {
		return mmDeleteTask.funcDeleteTask(ctx, requestID, user)
	}
	mmDeleteTask.t.Fatalf("Unexpected call to ServiceMock.DeleteTask. %v %v %v", ctx, requestID, user)
	return
}

// DeleteTaskAfterCounter returns a count of finished ServiceMock.DeleteTask invocations
func (mmDeleteTask *ServiceMock) DeleteTaskAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteTask.afterDeleteTaskCounter)
}

// DeleteTaskBeforeCounter returns a count of ServiceMock.DeleteTask invocations
func (mmDeleteTask *ServiceMock) DeleteTaskBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteTask.beforeDeleteTaskCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.DeleteTask.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteTask *mServiceMockDeleteTask) Calls() []*ServiceMockDeleteTaskParams {
	mmDeleteTask.mutex.RLock()

	argCopy := make([]*ServiceMockDeleteTaskParams, len(mmDeleteTask.callArgs))
	copy(argCopy, mmDeleteTask.callArgs)

	mmDeleteTask.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteTaskDone returns true if the count of the DeleteTask invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockDeleteTaskDone() bool {
	if m.DeleteTaskMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteTaskMock.invocationsDone()
}

// MinimockDeleteTaskInspect logs each unmet expectation
func (m *ServiceMock) MinimockDeleteTaskInspect() {
	for _, e := range m.DeleteTaskMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.DeleteTask at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteTaskCounter := mm_atomic.LoadUint64(&m.afterDeleteTaskCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteTaskMock.defaultExpectation != nil && afterDeleteTaskCounter < 1 {
		if m.DeleteTaskMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.DeleteTask at\n%s", m.DeleteTaskMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.DeleteTask at\n%s with params: %#v", m.DeleteTaskMock.defaultExpectation.expectationOrigins.origin, *m.DeleteTaskMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteTask != nil && afterDeleteTaskCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.DeleteTask at\n%s", m.funcDeleteTaskOrigin)
	}

	if !m.DeleteTaskMock.invocationsDone() && afterDeleteTaskCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.DeleteTask at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteTaskMock.expectedInvocations), m.DeleteTaskMock.expectedInvocationsOrigin, afterDeleteTaskCounter)
	}
}

type mServiceMockUpsertUser struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockUpsertUserExpectation
	expectations       []*ServiceMockUpsertUserExpectation

	callArgs []*ServiceMockUpsertUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockUpsertUserExpectation specifies expectation struct of the Service.UpsertUser
type ServiceMockUpsertUserExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockUpsertUserParams
	paramPtrs          *ServiceMockUpsertUserParamPtrs
	expectationOrigins ServiceMockUpsertUserExpectationOrigins
	results            *ServiceMockUpsertUserResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockUpsertUserParams contains parameters of the Service.UpsertUser
type ServiceMockUpsertUserParams struct {
	ctx       context.Context
	requestID string
	user      *model.User
}

// ServiceMockUpsertUserParamPtrs contains pointers to parameters of the Service.UpsertUser
type ServiceMockUpsertUserParamPtrs struct {
	ctx       *context.Context
	requestID *string
	user      **model.User
}

// ServiceMockUpsertUserResults contains results of the Service.UpsertUser
type ServiceMockUpsertUserResults struct {
	err error
}

// ServiceMockUpsertUserOrigins contains origins of expectations of the Service.UpsertUser
type ServiceMockUpsertUserExpectationOrigins struct {
	origin          string
	originCtx       string
	originRequestID string
	originUser      string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpsertUser *mServiceMockUpsertUser) Optional() *mServiceMockUpsertUser {
	mmUpsertUser.optional = true
	return mmUpsertUser
}

// Expect sets up expected params for Service.UpsertUser
func (mmUpsertUser *mServiceMockUpsertUser) Expect(ctx context.Context, requestID string, user *model.User) *mServiceMockUpsertUser {
	if mmUpsertUser.mock.funcUpsertUser != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Set")
	}

	if mmUpsertUser.defaultExpectation == nil {
		mmUpsertUser.defaultExpectation = &ServiceMockUpsertUserExpectation{}
	}

	if mmUpsertUser.defaultExpectation.paramPtrs != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by ExpectParams functions")
	}

	mmUpsertUser.defaultExpectation.params = &ServiceMockUpsertUserParams{ctx, requestID, user}
	mmUpsertUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpsertUser.expectations {
		if minimock.Equal(e.params, mmUpsertUser.defaultExpectation.params) {
			mmUpsertUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpsertUser.defaultExpectation.params)
		}
	}

	return mmUpsertUser
}

// ExpectCtxParam1 sets up expected param ctx for Service.UpsertUser
func (mmUpsertUser *mServiceMockUpsertUser) ExpectCtxParam1(ctx context.Context) *mServiceMockUpsertUser {
	if mmUpsertUser.mock.funcUpsertUser != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Set")
	}

	if mmUpsertUser.defaultExpectation == nil {
		mmUpsertUser.defaultExpectation = &ServiceMockUpsertUserExpectation{}
	}

	if mmUpsertUser.defaultExpectation.params != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Expect")
	}

	if mmUpsertUser.defaultExpectation.paramPtrs == nil {
		mmUpsertUser.defaultExpectation.paramPtrs = &ServiceMockUpsertUserParamPtrs{}
	}
	mmUpsertUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpsertUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpsertUser
}

// ExpectRequestIDParam2 sets up expected param requestID for Service.UpsertUser
func (mmUpsertUser *mServiceMockUpsertUser) ExpectRequestIDParam2(requestID string) *mServiceMockUpsertUser {
	if mmUpsertUser.mock.funcUpsertUser != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Set")
	}

	if mmUpsertUser.defaultExpectation == nil {
		mmUpsertUser.defaultExpectation = &ServiceMockUpsertUserExpectation{}
	}

	if mmUpsertUser.defaultExpectation.params != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Expect")
	}

	if mmUpsertUser.defaultExpectation.paramPtrs == nil {
		mmUpsertUser.defaultExpectation.paramPtrs = &ServiceMockUpsertUserParamPtrs{}
	}
	mmUpsertUser.defaultExpectation.paramPtrs.requestID = &requestID
	mmUpsertUser.defaultExpectation.expectationOrigins.originRequestID = minimock.CallerInfo(1)

	return mmUpsertUser
}

// ExpectUserParam3 sets up expected param user for Service.UpsertUser
func (mmUpsertUser *mServiceMockUpsertUser) ExpectUserParam3(user *model.User) *mServiceMockUpsertUser {
	if mmUpsertUser.mock.funcUpsertUser != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Set")
	}

	if mmUpsertUser.defaultExpectation == nil {
		mmUpsertUser.defaultExpectation = &ServiceMockUpsertUserExpectation{}
	}

	if mmUpsertUser.defaultExpectation.params != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Expect")
	}

	if mmUpsertUser.defaultExpectation.paramPtrs == nil {
		mmUpsertUser.defaultExpectation.paramPtrs = &ServiceMockUpsertUserParamPtrs{}
	}
	mmUpsertUser.defaultExpectation.paramPtrs.user = &user
	mmUpsertUser.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmUpsertUser
}

// Inspect accepts an inspector function that has same arguments as the Service.UpsertUser
func (mmUpsertUser *mServiceMockUpsertUser) Inspect(f func(ctx context.Context, requestID string, user *model.User)) *mServiceMockUpsertUser {
	if mmUpsertUser.mock.inspectFuncUpsertUser != nil {
		mmUpsertUser.mock.t.Fatalf("Inspect function is already set for ServiceMock.UpsertUser")
	}

	mmUpsertUser.mock.inspectFuncUpsertUser = f

	return mmUpsertUser
}

// Return sets up results that will be returned by Service.UpsertUser
func (mmUpsertUser *mServiceMockUpsertUser) Return(err error) *ServiceMock {
	if mmUpsertUser.mock.funcUpsertUser != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Set")
	}

	if mmUpsertUser.defaultExpectation == nil {
		mmUpsertUser.defaultExpectation = &ServiceMockUpsertUserExpectation{mock: mmUpsertUser.mock}
	}
	mmUpsertUser.defaultExpectation.results = &ServiceMockUpsertUserResults{err}
	mmUpsertUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpsertUser.mock
}

// Set uses given function f to mock the Service.UpsertUser method
func (mmUpsertUser *mServiceMockUpsertUser) Set(f func(ctx context.Context, requestID string, user *model.User) (err error)) *ServiceMock {
	if mmUpsertUser.defaultExpectation != nil {
		mmUpsertUser.mock.t.Fatalf("Default expectation is already set for the Service.UpsertUser method")
	}

	if len(mmUpsertUser.expectations) > 0 {
		mmUpsertUser.mock.t.Fatalf("Some expectations are already set for the Service.UpsertUser method")
	}

	mmUpsertUser.mock.funcUpsertUser = f
	mmUpsertUser.mock.funcUpsertUserOrigin = minimock.CallerInfo(1)
	return mmUpsertUser.mock
}

// When sets expectation for the Service.UpsertUser which will trigger the result defined by the following
// Then helper
func (mmUpsertUser *mServiceMockUpsertUser) When(ctx context.Context, requestID string, user *model.User) *ServiceMockUpsertUserExpectation {
	if mmUpsertUser.mock.funcUpsertUser != nil {
		mmUpsertUser.mock.t.Fatalf("ServiceMock.UpsertUser mock is already set by Set")
	}

	expectation := &ServiceMockUpsertUserExpectation{
		mock:               mmUpsertUser.mock,
		params:             &ServiceMockUpsertUserParams{ctx, requestID, user},
		expectationOrigins: ServiceMockUpsertUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpsertUser.expectations = append(mmUpsertUser.expectations, expectation)
	return expectation
}

// Then sets up Service.UpsertUser return parameters for the expectation previously defined by the When method
func (e *ServiceMockUpsertUserExpectation) Then(err error) *ServiceMock {
	e.results = &ServiceMockUpsertUserResults{err}
	return e.mock
}

// Times sets number of times Service.UpsertUser should be invoked
func (mmUpsertUser *mServiceMockUpsertUser) Times(n uint64) *mServiceMockUpsertUser {
	if n == 0 {
		mmUpsertUser.mock.t.Fatalf("Times of ServiceMock.UpsertUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpsertUser.expectedInvocations, n)
	mmUpsertUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpsertUser
}

func (mmUpsertUser *mServiceMockUpsertUser) invocationsDone() bool {
	if len(mmUpsertUser.expectations) == 0 && mmUpsertUser.defaultExpectation == nil && mmUpsertUser.mock.funcUpsertUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpsertUser.mock.afterUpsertUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpsertUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpsertUser implements mm_transport.Service
func (mmUpsertUser *ServiceMock) UpsertUser(ctx context.Context, requestID string, user *model.User) (err error) {
	mm_atomic.AddUint64(&mmUpsertUser.beforeUpsertUserCounter, 1)
	defer mm_atomic.AddUint64(&mmUpsertUser.afterUpsertUserCounter, 1)

	mmUpsertUser.t.Helper()

	if mmUpsertUser.inspectFuncUpsertUser != nil {
		mmUpsertUser.inspectFuncUpsertUser(ctx, requestID, user)
	}

	mm_params := ServiceMockUpsertUserParams{ctx, requestID, user}

	// Record call args
	mmUpsertUser.UpsertUserMock.mutex.Lock()
	mmUpsertUser.UpsertUserMock.callArgs = append(mmUpsertUser.UpsertUserMock.callArgs, &mm_params)
	mmUpsertUser.UpsertUserMock.mutex.Unlock()

	for _, e := range mmUpsertUser.UpsertUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpsertUser.UpsertUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpsertUser.UpsertUserMock.defaultExpectation.Counter, 1)
		mm_want := mmUpsertUser.UpsertUserMock.defaultExpectation.params
		mm_want_ptrs := mmUpsertUser.UpsertUserMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockUpsertUserParams{ctx, requestID, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpsertUser.t.Errorf("ServiceMock.UpsertUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpsertUser.UpsertUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.requestID != nil && !minimock.Equal(*mm_want_ptrs.requestID, mm_got.requestID) {
				mmUpsertUser.t.Errorf("ServiceMock.UpsertUser got unexpected parameter requestID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpsertUser.UpsertUserMock.defaultExpectation.expectationOrigins.originRequestID, *mm_want_ptrs.requestID, mm_got.requestID, minimock.Diff(*mm_want_ptrs.requestID, mm_got.requestID))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmUpsertUser.t.Errorf("ServiceMock.UpsertUser got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpsertUser.UpsertUserMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpsertUser.t.Errorf("ServiceMock.UpsertUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpsertUser.UpsertUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpsertUser.UpsertUserMock.defaultExpectation.results
		if mm_results == nil {
			mmUpsertUser.t.Fatal("No results are set for the ServiceMock.UpsertUser")
		}
		return (*mm_results).err
	}
	if mmUpsertUser.funcUpsertUser != nil {
		return mmUpsertUser.funcUpsertUser(ctx, requestID, user)
	}
	mmUpsertUser.t.Fatalf("Unexpected call to ServiceMock.UpsertUser. %v %v %v", ctx, requestID, user)
	return
}

// UpsertUserAfterCounter returns a count of finished ServiceMock.UpsertUser invocations
func (mmUpsertUser *ServiceMock) UpsertUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpsertUser.afterUpsertUserCounter)
}

// UpsertUserBeforeCounter returns a count of ServiceMock.UpsertUser invocations
func (mmUpsertUser *ServiceMock) UpsertUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpsertUser.beforeUpsertUserCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.UpsertUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpsertUser *mServiceMockUpsertUser) Calls() []*ServiceMockUpsertUserParams {
	mmUpsertUser.mutex.RLock()

	argCopy := make([]*ServiceMockUpsertUserParams, len(mmUpsertUser.callArgs))
	copy(argCopy, mmUpsertUser.callArgs)

	mmUpsertUser.mutex.RUnlock()

	return argCopy
}

// MinimockUpsertUserDone returns true if the count of the UpsertUser invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockUpsertUserDone() bool {
	if m.UpsertUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpsertUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpsertUserMock.invocationsDone()
}

// MinimockUpsertUserInspect logs each unmet expectation
func (m *ServiceMock) MinimockUpsertUserInspect() {
	for _, e := range m.UpsertUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.UpsertUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpsertUserCounter := mm_atomic.LoadUint64(&m.afterUpsertUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpsertUserMock.defaultExpectation != nil && afterUpsertUserCounter < 1 {
		if m.UpsertUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.UpsertUser at\n%s", m.UpsertUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.UpsertUser at\n%s with params: %#v", m.UpsertUserMock.defaultExpectation.expectationOrigins.origin, *m.UpsertUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpsertUser != nil && afterUpsertUserCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.UpsertUser at\n%s", m.funcUpsertUserOrigin)
	}

	if !m.UpsertUserMock.invocationsDone() && afterUpsertUserCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.UpsertUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpsertUserMock.expectedInvocations), m.UpsertUserMock.expectedInvocationsOrigin, afterUpsertUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteTaskInspect()

			m.MinimockUpsertUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteTaskDone() &&
		m.MinimockUpsertUserDone()
}
