// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"agent/internal/model"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// SenderMock implements mm_service.Sender
type SenderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSendError          func(ctx context.Context, msg *model.OutboundError) (err error)
	funcSendErrorOrigin    string
	inspectFuncSendError   func(ctx context.Context, msg *model.OutboundError)
	afterSendErrorCounter  uint64
	beforeSendErrorCounter uint64
	SendErrorMock          mSenderMockSendError

	funcSendRemoveAck          func(ctx context.Context, msg *model.OutboundRemove) (err error)
	funcSendRemoveAckOrigin    string
	inspectFuncSendRemoveAck   func(ctx context.Context, msg *model.OutboundRemove)
	afterSendRemoveAckCounter  uint64
	beforeSendRemoveAckCounter uint64
	SendRemoveAckMock          mSenderMockSendRemoveAck

	funcSendStats          func(ctx context.Context, msg *model.OutboundStats) (err error)
	funcSendStatsOrigin    string
	inspectFuncSendStats   func(ctx context.Context, msg *model.OutboundStats)
	afterSendStatsCounter  uint64
	beforeSendStatsCounter uint64
	SendStatsMock          mSenderMockSendStats

	funcSendUpsertAck          func(ctx context.Context, msg *model.OutboundUpsert) (err error)
	funcSendUpsertAckOrigin    string
	inspectFuncSendUpsertAck   func(ctx context.Context, msg *model.OutboundUpsert)
	afterSendUpsertAckCounter  uint64
	beforeSendUpsertAckCounter uint64
	SendUpsertAckMock          mSenderMockSendUpsertAck
}

// NewSenderMock returns a mock for mm_service.Sender
func NewSenderMock(t minimock.Tester) *SenderMock {
	m := &SenderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendErrorMock = mSenderMockSendError{mock: m}
	m.SendErrorMock.callArgs = []*SenderMockSendErrorParams{}

	m.SendRemoveAckMock = mSenderMockSendRemoveAck{mock: m}
	m.SendRemoveAckMock.callArgs = []*SenderMockSendRemoveAckParams{}

	m.SendStatsMock = mSenderMockSendStats{mock: m}
	m.SendStatsMock.callArgs = []*SenderMockSendStatsParams{}

	m.SendUpsertAckMock = mSenderMockSendUpsertAck{mock: m}
	m.SendUpsertAckMock.callArgs = []*SenderMockSendUpsertAckParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSenderMockSendError struct {
	optional           bool
	mock               *SenderMock
	defaultExpectation *SenderMockSendErrorExpectation
	expectations       []*SenderMockSendErrorExpectation

	callArgs []*SenderMockSendErrorParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SenderMockSendErrorExpectation specifies expectation struct of the Sender.SendError
type SenderMockSendErrorExpectation struct {
	mock               *SenderMock
	params             *SenderMockSendErrorParams
	paramPtrs          *SenderMockSendErrorParamPtrs
	expectationOrigins SenderMockSendErrorExpectationOrigins
	results            *SenderMockSendErrorResults
	returnOrigin       string
	Counter            uint64
}

// SenderMockSendErrorParams contains parameters of the Sender.SendError
type SenderMockSendErrorParams struct {
	ctx context.Context
	msg *model.OutboundError
}

// SenderMockSendErrorParamPtrs contains pointers to parameters of the Sender.SendError
type SenderMockSendErrorParamPtrs struct {
	ctx *context.Context
	msg **model.OutboundError
}

// SenderMockSendErrorResults contains results of the Sender.SendError
type SenderMockSendErrorResults struct {
	err error
}

// SenderMockSendErrorOrigins contains origins of expectations of the Sender.SendError
type SenderMockSendErrorExpectationOrigins struct {
	origin    string
	originCtx string
	originMsg string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendError *mSenderMockSendError) Optional() *mSenderMockSendError {
	mmSendError.optional = true
	return mmSendError
}

// Expect sets up expected params for Sender.SendError
func (mmSendError *mSenderMockSendError) Expect(ctx context.Context, msg *model.OutboundError) *mSenderMockSendError {
	if mmSendError.mock.funcSendError != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by Set")
	}

	if mmSendError.defaultExpectation == nil {
		mmSendError.defaultExpectation = &SenderMockSendErrorExpectation{}
	}

	if mmSendError.defaultExpectation.paramPtrs != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by ExpectParams functions")
	}

	mmSendError.defaultExpectation.params = &SenderMockSendErrorParams{ctx, msg}
	mmSendError.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendError.expectations {
		if minimock.Equal(e.params, mmSendError.defaultExpectation.params) {
			mmSendError.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendError.defaultExpectation.params)
		}
	}

	return mmSendError
}

// ExpectCtxParam1 sets up expected param ctx for Sender.SendError
func (mmSendError *mSenderMockSendError) ExpectCtxParam1(ctx context.Context) *mSenderMockSendError {
	if mmSendError.mock.funcSendError != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by Set")
	}

	if mmSendError.defaultExpectation == nil {
		mmSendError.defaultExpectation = &SenderMockSendErrorExpectation{}
	}

	if mmSendError.defaultExpectation.params != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by Expect")
	}

	if mmSendError.defaultExpectation.paramPtrs == nil {
		mmSendError.defaultExpectation.paramPtrs = &SenderMockSendErrorParamPtrs{}
	}
	mmSendError.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendError.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendError
}

// ExpectMsgParam2 sets up expected param msg for Sender.SendError
func (mmSendError *mSenderMockSendError) ExpectMsgParam2(msg *model.OutboundError) *mSenderMockSendError {
	if mmSendError.mock.funcSendError != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by Set")
	}

	if mmSendError.defaultExpectation == nil {
		mmSendError.defaultExpectation = &SenderMockSendErrorExpectation{}
	}

	if mmSendError.defaultExpectation.params != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by Expect")
	}

	if mmSendError.defaultExpectation.paramPtrs == nil {
		mmSendError.defaultExpectation.paramPtrs = &SenderMockSendErrorParamPtrs{}
	}
	mmSendError.defaultExpectation.paramPtrs.msg = &msg
	mmSendError.defaultExpectation.expectationOrigins.originMsg = minimock.CallerInfo(1)

	return mmSendError
}

// Inspect accepts an inspector function that has same arguments as the Sender.SendError
func (mmSendError *mSenderMockSendError) Inspect(f func(ctx context.Context, msg *model.OutboundError)) *mSenderMockSendError {
	if mmSendError.mock.inspectFuncSendError != nil {
		mmSendError.mock.t.Fatalf("Inspect function is already set for SenderMock.SendError")
	}

	mmSendError.mock.inspectFuncSendError = f

	return mmSendError
}

// Return sets up results that will be returned by Sender.SendError
func (mmSendError *mSenderMockSendError) Return(err error) *SenderMock {
	if mmSendError.mock.funcSendError != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by Set")
	}

	if mmSendError.defaultExpectation == nil {
		mmSendError.defaultExpectation = &SenderMockSendErrorExpectation{mock: mmSendError.mock}
	}
	mmSendError.defaultExpectation.results = &SenderMockSendErrorResults{err}
	mmSendError.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendError.mock
}

// Set uses given function f to mock the Sender.SendError method
func (mmSendError *mSenderMockSendError) Set(f func(ctx context.Context, msg *model.OutboundError) (err error)) *SenderMock {
	if mmSendError.defaultExpectation != nil {
		mmSendError.mock.t.Fatalf("Default expectation is already set for the Sender.SendError method")
	}

	if len(mmSendError.expectations) > 0 {
		mmSendError.mock.t.Fatalf("Some expectations are already set for the Sender.SendError method")
	}

	mmSendError.mock.funcSendError = f
	mmSendError.mock.funcSendErrorOrigin = minimock.CallerInfo(1)
	return mmSendError.mock
}

// When sets expectation for the Sender.SendError which will trigger the result defined by the following
// Then helper
func (mmSendError *mSenderMockSendError) When(ctx context.Context, msg *model.OutboundError) *SenderMockSendErrorExpectation {
	if mmSendError.mock.funcSendError != nil {
		mmSendError.mock.t.Fatalf("SenderMock.SendError mock is already set by Set")
	}

	expectation := &SenderMockSendErrorExpectation{
		mock:               mmSendError.mock,
		params:             &SenderMockSendErrorParams{ctx, msg},
		expectationOrigins: SenderMockSendErrorExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendError.expectations = append(mmSendError.expectations, expectation)
	return expectation
}

// Then sets up Sender.SendError return parameters for the expectation previously defined by the When method
func (e *SenderMockSendErrorExpectation) Then(err error) *SenderMock {
	e.results = &SenderMockSendErrorResults{err}
	return e.mock
}

// Times sets number of times Sender.SendError should be invoked
func (mmSendError *mSenderMockSendError) Times(n uint64) *mSenderMockSendError {
	if n == 0 {
		mmSendError.mock.t.Fatalf("Times of SenderMock.SendError mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendError.expectedInvocations, n)
	mmSendError.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendError
}

func (mmSendError *mSenderMockSendError) invocationsDone() bool {
	if len(mmSendError.expectations) == 0 && mmSendError.defaultExpectation == nil && mmSendError.mock.funcSendError == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendError.mock.afterSendErrorCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendError.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendError implements mm_service.Sender
func (mmSendError *SenderMock) SendError(ctx context.Context, msg *model.OutboundError) (err error) {
	mm_atomic.AddUint64(&mmSendError.beforeSendErrorCounter, 1)
	defer mm_atomic.AddUint64(&mmSendError.afterSendErrorCounter, 1)

	mmSendError.t.Helper()

	if mmSendError.inspectFuncSendError != nil {
		mmSendError.inspectFuncSendError(ctx, msg)
	}

	mm_params := SenderMockSendErrorParams{ctx, msg}

	// Record call args
	mmSendError.SendErrorMock.mutex.Lock()
	mmSendError.SendErrorMock.callArgs = append(mmSendError.SendErrorMock.callArgs, &mm_params)
	mmSendError.SendErrorMock.mutex.Unlock()

	for _, e := range mmSendError.SendErrorMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendError.SendErrorMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendError.SendErrorMock.defaultExpectation.Counter, 1)
		mm_want := mmSendError.SendErrorMock.defaultExpectation.params
		mm_want_ptrs := mmSendError.SendErrorMock.defaultExpectation.paramPtrs

		mm_got := SenderMockSendErrorParams{ctx, msg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendError.t.Errorf("SenderMock.SendError got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendError.SendErrorMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmSendError.t.Errorf("SenderMock.SendError got unexpected parameter msg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendError.SendErrorMock.defaultExpectation.expectationOrigins.originMsg, *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendError.t.Errorf("SenderMock.SendError got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendError.SendErrorMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendError.SendErrorMock.defaultExpectation.results
		if mm_results == nil {
			mmSendError.t.Fatal("No results are set for the SenderMock.SendError")
		}
		return (*mm_results).err
	}
	if mmSendError.funcSendError != nil {
		return mmSendError.funcSendError(ctx, msg)
	}
	mmSendError.t.Fatalf("Unexpected call to SenderMock.SendError. %v %v", ctx, msg)
	return
}

// SendErrorAfterCounter returns a count of finished SenderMock.SendError invocations
func (mmSendError *SenderMock) SendErrorAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendError.afterSendErrorCounter)
}

// SendErrorBeforeCounter returns a count of SenderMock.SendError invocations
func (mmSendError *SenderMock) SendErrorBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendError.beforeSendErrorCounter)
}

// Calls returns a list of arguments used in each call to SenderMock.SendError.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendError *mSenderMockSendError) Calls() []*SenderMockSendErrorParams {
	mmSendError.mutex.RLock()

	argCopy := make([]*SenderMockSendErrorParams, len(mmSendError.callArgs))
	copy(argCopy, mmSendError.callArgs)

	mmSendError.mutex.RUnlock()

	return argCopy
}

// MinimockSendErrorDone returns true if the count of the SendError invocations corresponds
// the number of defined expectations
func (m *SenderMock) MinimockSendErrorDone() bool {
	if m.SendErrorMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendErrorMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendErrorMock.invocationsDone()
}

// MinimockSendErrorInspect logs each unmet expectation
func (m *SenderMock) MinimockSendErrorInspect() {
	for _, e := range m.SendErrorMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SenderMock.SendError at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendErrorCounter := mm_atomic.LoadUint64(&m.afterSendErrorCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendErrorMock.defaultExpectation != nil && afterSendErrorCounter < 1 {
		if m.SendErrorMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SenderMock.SendError at\n%s", m.SendErrorMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SenderMock.SendError at\n%s with params: %#v", m.SendErrorMock.defaultExpectation.expectationOrigins.origin, *m.SendErrorMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendError != nil && afterSendErrorCounter < 1 {
		m.t.Errorf("Expected call to SenderMock.SendError at\n%s", m.funcSendErrorOrigin)
	}

	if !m.SendErrorMock.invocationsDone() && afterSendErrorCounter > 0 {
		m.t.Errorf("Expected %d calls to SenderMock.SendError at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendErrorMock.expectedInvocations), m.SendErrorMock.expectedInvocationsOrigin, afterSendErrorCounter)
	}
}

type mSenderMockSendRemoveAck struct {
	optional           bool
	mock               *SenderMock
	defaultExpectation *SenderMockSendRemoveAckExpectation
	expectations       []*SenderMockSendRemoveAckExpectation

	callArgs []*SenderMockSendRemoveAckParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SenderMockSendRemoveAckExpectation specifies expectation struct of the Sender.SendRemoveAck
type SenderMockSendRemoveAckExpectation struct {
	mock               *SenderMock
	params             *SenderMockSendRemoveAckParams
	paramPtrs          *SenderMockSendRemoveAckParamPtrs
	expectationOrigins SenderMockSendRemoveAckExpectationOrigins
	results            *SenderMockSendRemoveAckResults
	returnOrigin       string
	Counter            uint64
}

// SenderMockSendRemoveAckParams contains parameters of the Sender.SendRemoveAck
type SenderMockSendRemoveAckParams struct {
	ctx context.Context
	msg *model.OutboundRemove
}

// SenderMockSendRemoveAckParamPtrs contains pointers to parameters of the Sender.SendRemoveAck
type SenderMockSendRemoveAckParamPtrs struct {
	ctx *context.Context
	msg **model.OutboundRemove
}

// SenderMockSendRemoveAckResults contains results of the Sender.SendRemoveAck
type SenderMockSendRemoveAckResults struct {
	err error
}

// SenderMockSendRemoveAckOrigins contains origins of expectations of the Sender.SendRemoveAck
type SenderMockSendRemoveAckExpectationOrigins struct {
	origin    string
	originCtx string
	originMsg string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendRemoveAck *mSenderMockSendRemoveAck) Optional() *mSenderMockSendRemoveAck {
	mmSendRemoveAck.optional = true
	return mmSendRemoveAck
}

// Expect sets up expected params for Sender.SendRemoveAck
func (mmSendRemoveAck *mSenderMockSendRemoveAck) Expect(ctx context.Context, msg *model.OutboundRemove) *mSenderMockSendRemoveAck {
	if mmSendRemoveAck.mock.funcSendRemoveAck != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by Set")
	}

	if mmSendRemoveAck.defaultExpectation == nil {
		mmSendRemoveAck.defaultExpectation = &SenderMockSendRemoveAckExpectation{}
	}

	if mmSendRemoveAck.defaultExpectation.paramPtrs != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by ExpectParams functions")
	}

	mmSendRemoveAck.defaultExpectation.params = &SenderMockSendRemoveAckParams{ctx, msg}
	mmSendRemoveAck.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendRemoveAck.expectations {
		if minimock.Equal(e.params, mmSendRemoveAck.defaultExpectation.params) {
			mmSendRemoveAck.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendRemoveAck.defaultExpectation.params)
		}
	}

	return mmSendRemoveAck
}

// ExpectCtxParam1 sets up expected param ctx for Sender.SendRemoveAck
func (mmSendRemoveAck *mSenderMockSendRemoveAck) ExpectCtxParam1(ctx context.Context) *mSenderMockSendRemoveAck {
	if mmSendRemoveAck.mock.funcSendRemoveAck != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by Set")
	}

	if mmSendRemoveAck.defaultExpectation == nil {
		mmSendRemoveAck.defaultExpectation = &SenderMockSendRemoveAckExpectation{}
	}

	if mmSendRemoveAck.defaultExpectation.params != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by Expect")
	}

	if mmSendRemoveAck.defaultExpectation.paramPtrs == nil {
		mmSendRemoveAck.defaultExpectation.paramPtrs = &SenderMockSendRemoveAckParamPtrs{}
	}
	mmSendRemoveAck.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendRemoveAck.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendRemoveAck
}

// ExpectMsgParam2 sets up expected param msg for Sender.SendRemoveAck
func (mmSendRemoveAck *mSenderMockSendRemoveAck) ExpectMsgParam2(msg *model.OutboundRemove) *mSenderMockSendRemoveAck {
	if mmSendRemoveAck.mock.funcSendRemoveAck != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by Set")
	}

	if mmSendRemoveAck.defaultExpectation == nil {
		mmSendRemoveAck.defaultExpectation = &SenderMockSendRemoveAckExpectation{}
	}

	if mmSendRemoveAck.defaultExpectation.params != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by Expect")
	}

	if mmSendRemoveAck.defaultExpectation.paramPtrs == nil {
		mmSendRemoveAck.defaultExpectation.paramPtrs = &SenderMockSendRemoveAckParamPtrs{}
	}
	mmSendRemoveAck.defaultExpectation.paramPtrs.msg = &msg
	mmSendRemoveAck.defaultExpectation.expectationOrigins.originMsg = minimock.CallerInfo(1)

	return mmSendRemoveAck
}

// Inspect accepts an inspector function that has same arguments as the Sender.SendRemoveAck
func (mmSendRemoveAck *mSenderMockSendRemoveAck) Inspect(f func(ctx context.Context, msg *model.OutboundRemove)) *mSenderMockSendRemoveAck {
	if mmSendRemoveAck.mock.inspectFuncSendRemoveAck != nil {
		mmSendRemoveAck.mock.t.Fatalf("Inspect function is already set for SenderMock.SendRemoveAck")
	}

	mmSendRemoveAck.mock.inspectFuncSendRemoveAck = f

	return mmSendRemoveAck
}

// Return sets up results that will be returned by Sender.SendRemoveAck
func (mmSendRemoveAck *mSenderMockSendRemoveAck) Return(err error) *SenderMock {
	if mmSendRemoveAck.mock.funcSendRemoveAck != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by Set")
	}

	if mmSendRemoveAck.defaultExpectation == nil {
		mmSendRemoveAck.defaultExpectation = &SenderMockSendRemoveAckExpectation{mock: mmSendRemoveAck.mock}
	}
	mmSendRemoveAck.defaultExpectation.results = &SenderMockSendRemoveAckResults{err}
	mmSendRemoveAck.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendRemoveAck.mock
}

// Set uses given function f to mock the Sender.SendRemoveAck method
func (mmSendRemoveAck *mSenderMockSendRemoveAck) Set(f func(ctx context.Context, msg *model.OutboundRemove) (err error)) *SenderMock {
	if mmSendRemoveAck.defaultExpectation != nil {
		mmSendRemoveAck.mock.t.Fatalf("Default expectation is already set for the Sender.SendRemoveAck method")
	}

	if len(mmSendRemoveAck.expectations) > 0 {
		mmSendRemoveAck.mock.t.Fatalf("Some expectations are already set for the Sender.SendRemoveAck method")
	}

	mmSendRemoveAck.mock.funcSendRemoveAck = f
	mmSendRemoveAck.mock.funcSendRemoveAckOrigin = minimock.CallerInfo(1)
	return mmSendRemoveAck.mock
}

// When sets expectation for the Sender.SendRemoveAck which will trigger the result defined by the following
// Then helper
func (mmSendRemoveAck *mSenderMockSendRemoveAck) When(ctx context.Context, msg *model.OutboundRemove) *SenderMockSendRemoveAckExpectation {
	if mmSendRemoveAck.mock.funcSendRemoveAck != nil {
		mmSendRemoveAck.mock.t.Fatalf("SenderMock.SendRemoveAck mock is already set by Set")
	}

	expectation := &SenderMockSendRemoveAckExpectation{
		mock:               mmSendRemoveAck.mock,
		params:             &SenderMockSendRemoveAckParams{ctx, msg},
		expectationOrigins: SenderMockSendRemoveAckExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendRemoveAck.expectations = append(mmSendRemoveAck.expectations, expectation)
	return expectation
}

// Then sets up Sender.SendRemoveAck return parameters for the expectation previously defined by the When method
func (e *SenderMockSendRemoveAckExpectation) Then(err error) *SenderMock {
	e.results = &SenderMockSendRemoveAckResults{err}
	return e.mock
}

// Times sets number of times Sender.SendRemoveAck should be invoked
func (mmSendRemoveAck *mSenderMockSendRemoveAck) Times(n uint64) *mSenderMockSendRemoveAck {
	if n == 0 {
		mmSendRemoveAck.mock.t.Fatalf("Times of SenderMock.SendRemoveAck mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendRemoveAck.expectedInvocations, n)
	mmSendRemoveAck.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendRemoveAck
}

func (mmSendRemoveAck *mSenderMockSendRemoveAck) invocationsDone() bool {
	if len(mmSendRemoveAck.expectations) == 0 && mmSendRemoveAck.defaultExpectation == nil && mmSendRemoveAck.mock.funcSendRemoveAck == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendRemoveAck.mock.afterSendRemoveAckCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendRemoveAck.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendRemoveAck implements mm_service.Sender
func (mmSendRemoveAck *SenderMock) SendRemoveAck(ctx context.Context, msg *model.OutboundRemove) (err error) {
	mm_atomic.AddUint64(&mmSendRemoveAck.beforeSendRemoveAckCounter, 1)
	defer mm_atomic.AddUint64(&mmSendRemoveAck.afterSendRemoveAckCounter, 1)

	mmSendRemoveAck.t.Helper()

	if mmSendRemoveAck.inspectFuncSendRemoveAck != nil {
		mmSendRemoveAck.inspectFuncSendRemoveAck(ctx, msg)
	}

	mm_params := SenderMockSendRemoveAckParams{ctx, msg}

	// Record call args
	mmSendRemoveAck.SendRemoveAckMock.mutex.Lock()
	mmSendRemoveAck.SendRemoveAckMock.callArgs = append(mmSendRemoveAck.SendRemoveAckMock.callArgs, &mm_params)
	mmSendRemoveAck.SendRemoveAckMock.mutex.Unlock()

	for _, e := range mmSendRemoveAck.SendRemoveAckMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendRemoveAck.SendRemoveAckMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendRemoveAck.SendRemoveAckMock.defaultExpectation.Counter, 1)
		mm_want := mmSendRemoveAck.SendRemoveAckMock.defaultExpectation.params
		mm_want_ptrs := mmSendRemoveAck.SendRemoveAckMock.defaultExpectation.paramPtrs

		mm_got := SenderMockSendRemoveAckParams{ctx, msg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendRemoveAck.t.Errorf("SenderMock.SendRemoveAck got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendRemoveAck.SendRemoveAckMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmSendRemoveAck.t.Errorf("SenderMock.SendRemoveAck got unexpected parameter msg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendRemoveAck.SendRemoveAckMock.defaultExpectation.expectationOrigins.originMsg, *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendRemoveAck.t.Errorf("SenderMock.SendRemoveAck got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendRemoveAck.SendRemoveAckMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendRemoveAck.SendRemoveAckMock.defaultExpectation.results
		if mm_results == nil {
			mmSendRemoveAck.t.Fatal("No results are set for the SenderMock.SendRemoveAck")
		}
		return (*mm_results).err
	}
	if mmSendRemoveAck.funcSendRemoveAck != nil {
		return mmSendRemoveAck.funcSendRemoveAck(ctx, msg)
	}
	mmSendRemoveAck.t.Fatalf("Unexpected call to SenderMock.SendRemoveAck. %v %v", ctx, msg)
	return
}

// SendRemoveAckAfterCounter returns a count of finished SenderMock.SendRemoveAck invocations
func (mmSendRemoveAck *SenderMock) SendRemoveAckAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendRemoveAck.afterSendRemoveAckCounter)
}

// SendRemoveAckBeforeCounter returns a count of SenderMock.SendRemoveAck invocations
func (mmSendRemoveAck *SenderMock) SendRemoveAckBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendRemoveAck.beforeSendRemoveAckCounter)
}

// Calls returns a list of arguments used in each call to SenderMock.SendRemoveAck.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendRemoveAck *mSenderMockSendRemoveAck) Calls() []*SenderMockSendRemoveAckParams {
	mmSendRemoveAck.mutex.RLock()

	argCopy := make([]*SenderMockSendRemoveAckParams, len(mmSendRemoveAck.callArgs))
	copy(argCopy, mmSendRemoveAck.callArgs)

	mmSendRemoveAck.mutex.RUnlock()

	return argCopy
}

// MinimockSendRemoveAckDone returns true if the count of the SendRemoveAck invocations corresponds
// the number of defined expectations
func (m *SenderMock) MinimockSendRemoveAckDone() bool {
	if m.SendRemoveAckMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendRemoveAckMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendRemoveAckMock.invocationsDone()
}

// MinimockSendRemoveAckInspect logs each unmet expectation
func (m *SenderMock) MinimockSendRemoveAckInspect() {
	for _, e := range m.SendRemoveAckMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SenderMock.SendRemoveAck at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendRemoveAckCounter := mm_atomic.LoadUint64(&m.afterSendRemoveAckCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendRemoveAckMock.defaultExpectation != nil && afterSendRemoveAckCounter < 1 {
		if m.SendRemoveAckMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SenderMock.SendRemoveAck at\n%s", m.SendRemoveAckMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SenderMock.SendRemoveAck at\n%s with params: %#v", m.SendRemoveAckMock.defaultExpectation.expectationOrigins.origin, *m.SendRemoveAckMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendRemoveAck != nil && afterSendRemoveAckCounter < 1 {
		m.t.Errorf("Expected call to SenderMock.SendRemoveAck at\n%s", m.funcSendRemoveAckOrigin)
	}

	if !m.SendRemoveAckMock.invocationsDone() && afterSendRemoveAckCounter > 0 {
		m.t.Errorf("Expected %d calls to SenderMock.SendRemoveAck at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendRemoveAckMock.expectedInvocations), m.SendRemoveAckMock.expectedInvocationsOrigin, afterSendRemoveAckCounter)
	}
}

type mSenderMockSendStats struct {
	optional           bool
	mock               *SenderMock
	defaultExpectation *SenderMockSendStatsExpectation
	expectations       []*SenderMockSendStatsExpectation

	callArgs []*SenderMockSendStatsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SenderMockSendStatsExpectation specifies expectation struct of the Sender.SendStats
type SenderMockSendStatsExpectation struct {
	mock               *SenderMock
	params             *SenderMockSendStatsParams
	paramPtrs          *SenderMockSendStatsParamPtrs
	expectationOrigins SenderMockSendStatsExpectationOrigins
	results            *SenderMockSendStatsResults
	returnOrigin       string
	Counter            uint64
}

// SenderMockSendStatsParams contains parameters of the Sender.SendStats
type SenderMockSendStatsParams struct {
	ctx context.Context
	msg *model.OutboundStats
}

// SenderMockSendStatsParamPtrs contains pointers to parameters of the Sender.SendStats
type SenderMockSendStatsParamPtrs struct {
	ctx *context.Context
	msg **model.OutboundStats
}

// SenderMockSendStatsResults contains results of the Sender.SendStats
type SenderMockSendStatsResults struct {
	err error
}

// SenderMockSendStatsOrigins contains origins of expectations of the Sender.SendStats
type SenderMockSendStatsExpectationOrigins struct {
	origin    string
	originCtx string
	originMsg string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendStats *mSenderMockSendStats) Optional() *mSenderMockSendStats {
	mmSendStats.optional = true
	return mmSendStats
}

// Expect sets up expected params for Sender.SendStats
func (mmSendStats *mSenderMockSendStats) Expect(ctx context.Context, msg *model.OutboundStats) *mSenderMockSendStats {
	if mmSendStats.mock.funcSendStats != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by Set")
	}

	if mmSendStats.defaultExpectation == nil {
		mmSendStats.defaultExpectation = &SenderMockSendStatsExpectation{}
	}

	if mmSendStats.defaultExpectation.paramPtrs != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by ExpectParams functions")
	}

	mmSendStats.defaultExpectation.params = &SenderMockSendStatsParams{ctx, msg}
	mmSendStats.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendStats.expectations {
		if minimock.Equal(e.params, mmSendStats.defaultExpectation.params) {
			mmSendStats.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendStats.defaultExpectation.params)
		}
	}

	return mmSendStats
}

// ExpectCtxParam1 sets up expected param ctx for Sender.SendStats
func (mmSendStats *mSenderMockSendStats) ExpectCtxParam1(ctx context.Context) *mSenderMockSendStats {
	if mmSendStats.mock.funcSendStats != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by Set")
	}

	if mmSendStats.defaultExpectation == nil {
		mmSendStats.defaultExpectation = &SenderMockSendStatsExpectation{}
	}

	if mmSendStats.defaultExpectation.params != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by Expect")
	}

	if mmSendStats.defaultExpectation.paramPtrs == nil {
		mmSendStats.defaultExpectation.paramPtrs = &SenderMockSendStatsParamPtrs{}
	}
	mmSendStats.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendStats.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendStats
}

// ExpectMsgParam2 sets up expected param msg for Sender.SendStats
func (mmSendStats *mSenderMockSendStats) ExpectMsgParam2(msg *model.OutboundStats) *mSenderMockSendStats {
	if mmSendStats.mock.funcSendStats != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by Set")
	}

	if mmSendStats.defaultExpectation == nil {
		mmSendStats.defaultExpectation = &SenderMockSendStatsExpectation{}
	}

	if mmSendStats.defaultExpectation.params != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by Expect")
	}

	if mmSendStats.defaultExpectation.paramPtrs == nil {
		mmSendStats.defaultExpectation.paramPtrs = &SenderMockSendStatsParamPtrs{}
	}
	mmSendStats.defaultExpectation.paramPtrs.msg = &msg
	mmSendStats.defaultExpectation.expectationOrigins.originMsg = minimock.CallerInfo(1)

	return mmSendStats
}

// Inspect accepts an inspector function that has same arguments as the Sender.SendStats
func (mmSendStats *mSenderMockSendStats) Inspect(f func(ctx context.Context, msg *model.OutboundStats)) *mSenderMockSendStats {
	if mmSendStats.mock.inspectFuncSendStats != nil {
		mmSendStats.mock.t.Fatalf("Inspect function is already set for SenderMock.SendStats")
	}

	mmSendStats.mock.inspectFuncSendStats = f

	return mmSendStats
}

// Return sets up results that will be returned by Sender.SendStats
func (mmSendStats *mSenderMockSendStats) Return(err error) *SenderMock {
	if mmSendStats.mock.funcSendStats != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by Set")
	}

	if mmSendStats.defaultExpectation == nil {
		mmSendStats.defaultExpectation = &SenderMockSendStatsExpectation{mock: mmSendStats.mock}
	}
	mmSendStats.defaultExpectation.results = &SenderMockSendStatsResults{err}
	mmSendStats.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendStats.mock
}

// Set uses given function f to mock the Sender.SendStats method
func (mmSendStats *mSenderMockSendStats) Set(f func(ctx context.Context, msg *model.OutboundStats) (err error)) *SenderMock {
	if mmSendStats.defaultExpectation != nil {
		mmSendStats.mock.t.Fatalf("Default expectation is already set for the Sender.SendStats method")
	}

	if len(mmSendStats.expectations) > 0 {
		mmSendStats.mock.t.Fatalf("Some expectations are already set for the Sender.SendStats method")
	}

	mmSendStats.mock.funcSendStats = f
	mmSendStats.mock.funcSendStatsOrigin = minimock.CallerInfo(1)
	return mmSendStats.mock
}

// When sets expectation for the Sender.SendStats which will trigger the result defined by the following
// Then helper
func (mmSendStats *mSenderMockSendStats) When(ctx context.Context, msg *model.OutboundStats) *SenderMockSendStatsExpectation {
	if mmSendStats.mock.funcSendStats != nil {
		mmSendStats.mock.t.Fatalf("SenderMock.SendStats mock is already set by Set")
	}

	expectation := &SenderMockSendStatsExpectation{
		mock:               mmSendStats.mock,
		params:             &SenderMockSendStatsParams{ctx, msg},
		expectationOrigins: SenderMockSendStatsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendStats.expectations = append(mmSendStats.expectations, expectation)
	return expectation
}

// Then sets up Sender.SendStats return parameters for the expectation previously defined by the When method
func (e *SenderMockSendStatsExpectation) Then(err error) *SenderMock {
	e.results = &SenderMockSendStatsResults{err}
	return e.mock
}

// Times sets number of times Sender.SendStats should be invoked
func (mmSendStats *mSenderMockSendStats) Times(n uint64) *mSenderMockSendStats {
	if n == 0 {
		mmSendStats.mock.t.Fatalf("Times of SenderMock.SendStats mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendStats.expectedInvocations, n)
	mmSendStats.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendStats
}

func (mmSendStats *mSenderMockSendStats) invocationsDone() bool {
	if len(mmSendStats.expectations) == 0 && mmSendStats.defaultExpectation == nil && mmSendStats.mock.funcSendStats == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendStats.mock.afterSendStatsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendStats.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendStats implements mm_service.Sender
func (mmSendStats *SenderMock) SendStats(ctx context.Context, msg *model.OutboundStats) (err error) {
	mm_atomic.AddUint64(&mmSendStats.beforeSendStatsCounter, 1)
	defer mm_atomic.AddUint64(&mmSendStats.afterSendStatsCounter, 1)

	mmSendStats.t.Helper()

	if mmSendStats.inspectFuncSendStats != nil {
		mmSendStats.inspectFuncSendStats(ctx, msg)
	}

	mm_params := SenderMockSendStatsParams{ctx, msg}

	// Record call args
	mmSendStats.SendStatsMock.mutex.Lock()
	mmSendStats.SendStatsMock.callArgs = append(mmSendStats.SendStatsMock.callArgs, &mm_params)
	mmSendStats.SendStatsMock.mutex.Unlock()

	for _, e := range mmSendStats.SendStatsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendStats.SendStatsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendStats.SendStatsMock.defaultExpectation.Counter, 1)
		mm_want := mmSendStats.SendStatsMock.defaultExpectation.params
		mm_want_ptrs := mmSendStats.SendStatsMock.defaultExpectation.paramPtrs

		mm_got := SenderMockSendStatsParams{ctx, msg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendStats.t.Errorf("SenderMock.SendStats got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendStats.SendStatsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmSendStats.t.Errorf("SenderMock.SendStats got unexpected parameter msg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendStats.SendStatsMock.defaultExpectation.expectationOrigins.originMsg, *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendStats.t.Errorf("SenderMock.SendStats got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendStats.SendStatsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendStats.SendStatsMock.defaultExpectation.results
		if mm_results == nil {
			mmSendStats.t.Fatal("No results are set for the SenderMock.SendStats")
		}
		return (*mm_results).err
	}
	if mmSendStats.funcSendStats != nil {
		return mmSendStats.funcSendStats(ctx, msg)
	}
	mmSendStats.t.Fatalf("Unexpected call to SenderMock.SendStats. %v %v", ctx, msg)
	return
}

// SendStatsAfterCounter returns a count of finished SenderMock.SendStats invocations
func (mmSendStats *SenderMock) SendStatsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendStats.afterSendStatsCounter)
}

// SendStatsBeforeCounter returns a count of SenderMock.SendStats invocations
func (mmSendStats *SenderMock) SendStatsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendStats.beforeSendStatsCounter)
}

// Calls returns a list of arguments used in each call to SenderMock.SendStats.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendStats *mSenderMockSendStats) Calls() []*SenderMockSendStatsParams {
	mmSendStats.mutex.RLock()

	argCopy := make([]*SenderMockSendStatsParams, len(mmSendStats.callArgs))
	copy(argCopy, mmSendStats.callArgs)

	mmSendStats.mutex.RUnlock()

	return argCopy
}

// MinimockSendStatsDone returns true if the count of the SendStats invocations corresponds
// the number of defined expectations
func (m *SenderMock) MinimockSendStatsDone() bool {
	if m.SendStatsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendStatsMock.invocationsDone()
}

// MinimockSendStatsInspect logs each unmet expectation
func (m *SenderMock) MinimockSendStatsInspect() {
	for _, e := range m.SendStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SenderMock.SendStats at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendStatsCounter := mm_atomic.LoadUint64(&m.afterSendStatsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendStatsMock.defaultExpectation != nil && afterSendStatsCounter < 1 {
		if m.SendStatsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SenderMock.SendStats at\n%s", m.SendStatsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SenderMock.SendStats at\n%s with params: %#v", m.SendStatsMock.defaultExpectation.expectationOrigins.origin, *m.SendStatsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendStats != nil && afterSendStatsCounter < 1 {
		m.t.Errorf("Expected call to SenderMock.SendStats at\n%s", m.funcSendStatsOrigin)
	}

	if !m.SendStatsMock.invocationsDone() && afterSendStatsCounter > 0 {
		m.t.Errorf("Expected %d calls to SenderMock.SendStats at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendStatsMock.expectedInvocations), m.SendStatsMock.expectedInvocationsOrigin, afterSendStatsCounter)
	}
}

type mSenderMockSendUpsertAck struct {
	optional           bool
	mock               *SenderMock
	defaultExpectation *SenderMockSendUpsertAckExpectation
	expectations       []*SenderMockSendUpsertAckExpectation

	callArgs []*SenderMockSendUpsertAckParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SenderMockSendUpsertAckExpectation specifies expectation struct of the Sender.SendUpsertAck
type SenderMockSendUpsertAckExpectation struct {
	mock               *SenderMock
	params             *SenderMockSendUpsertAckParams
	paramPtrs          *SenderMockSendUpsertAckParamPtrs
	expectationOrigins SenderMockSendUpsertAckExpectationOrigins
	results            *SenderMockSendUpsertAckResults
	returnOrigin       string
	Counter            uint64
}

// SenderMockSendUpsertAckParams contains parameters of the Sender.SendUpsertAck
type SenderMockSendUpsertAckParams struct {
	ctx context.Context
	msg *model.OutboundUpsert
}

// SenderMockSendUpsertAckParamPtrs contains pointers to parameters of the Sender.SendUpsertAck
type SenderMockSendUpsertAckParamPtrs struct {
	ctx *context.Context
	msg **model.OutboundUpsert
}

// SenderMockSendUpsertAckResults contains results of the Sender.SendUpsertAck
type SenderMockSendUpsertAckResults struct {
	err error
}

// SenderMockSendUpsertAckOrigins contains origins of expectations of the Sender.SendUpsertAck
type SenderMockSendUpsertAckExpectationOrigins struct {
	origin    string
	originCtx string
	originMsg string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendUpsertAck *mSenderMockSendUpsertAck) Optional() *mSenderMockSendUpsertAck {
	mmSendUpsertAck.optional = true
	return mmSendUpsertAck
}

// Expect sets up expected params for Sender.SendUpsertAck
func (mmSendUpsertAck *mSenderMockSendUpsertAck) Expect(ctx context.Context, msg *model.OutboundUpsert) *mSenderMockSendUpsertAck {
	if mmSendUpsertAck.mock.funcSendUpsertAck != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by Set")
	}

	if mmSendUpsertAck.defaultExpectation == nil {
		mmSendUpsertAck.defaultExpectation = &SenderMockSendUpsertAckExpectation{}
	}

	if mmSendUpsertAck.defaultExpectation.paramPtrs != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by ExpectParams functions")
	}

	mmSendUpsertAck.defaultExpectation.params = &SenderMockSendUpsertAckParams{ctx, msg}
	mmSendUpsertAck.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendUpsertAck.expectations {
		if minimock.Equal(e.params, mmSendUpsertAck.defaultExpectation.params) {
			mmSendUpsertAck.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendUpsertAck.defaultExpectation.params)
		}
	}

	return mmSendUpsertAck
}

// ExpectCtxParam1 sets up expected param ctx for Sender.SendUpsertAck
func (mmSendUpsertAck *mSenderMockSendUpsertAck) ExpectCtxParam1(ctx context.Context) *mSenderMockSendUpsertAck {
	if mmSendUpsertAck.mock.funcSendUpsertAck != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by Set")
	}

	if mmSendUpsertAck.defaultExpectation == nil {
		mmSendUpsertAck.defaultExpectation = &SenderMockSendUpsertAckExpectation{}
	}

	if mmSendUpsertAck.defaultExpectation.params != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by Expect")
	}

	if mmSendUpsertAck.defaultExpectation.paramPtrs == nil {
		mmSendUpsertAck.defaultExpectation.paramPtrs = &SenderMockSendUpsertAckParamPtrs{}
	}
	mmSendUpsertAck.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendUpsertAck.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendUpsertAck
}

// ExpectMsgParam2 sets up expected param msg for Sender.SendUpsertAck
func (mmSendUpsertAck *mSenderMockSendUpsertAck) ExpectMsgParam2(msg *model.OutboundUpsert) *mSenderMockSendUpsertAck {
	if mmSendUpsertAck.mock.funcSendUpsertAck != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by Set")
	}

	if mmSendUpsertAck.defaultExpectation == nil {
		mmSendUpsertAck.defaultExpectation = &SenderMockSendUpsertAckExpectation{}
	}

	if mmSendUpsertAck.defaultExpectation.params != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by Expect")
	}

	if mmSendUpsertAck.defaultExpectation.paramPtrs == nil {
		mmSendUpsertAck.defaultExpectation.paramPtrs = &SenderMockSendUpsertAckParamPtrs{}
	}
	mmSendUpsertAck.defaultExpectation.paramPtrs.msg = &msg
	mmSendUpsertAck.defaultExpectation.expectationOrigins.originMsg = minimock.CallerInfo(1)

	return mmSendUpsertAck
}

// Inspect accepts an inspector function that has same arguments as the Sender.SendUpsertAck
func (mmSendUpsertAck *mSenderMockSendUpsertAck) Inspect(f func(ctx context.Context, msg *model.OutboundUpsert)) *mSenderMockSendUpsertAck {
	if mmSendUpsertAck.mock.inspectFuncSendUpsertAck != nil {
		mmSendUpsertAck.mock.t.Fatalf("Inspect function is already set for SenderMock.SendUpsertAck")
	}

	mmSendUpsertAck.mock.inspectFuncSendUpsertAck = f

	return mmSendUpsertAck
}

// Return sets up results that will be returned by Sender.SendUpsertAck
func (mmSendUpsertAck *mSenderMockSendUpsertAck) Return(err error) *SenderMock {
	if mmSendUpsertAck.mock.funcSendUpsertAck != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by Set")
	}

	if mmSendUpsertAck.defaultExpectation == nil {
		mmSendUpsertAck.defaultExpectation = &SenderMockSendUpsertAckExpectation{mock: mmSendUpsertAck.mock}
	}
	mmSendUpsertAck.defaultExpectation.results = &SenderMockSendUpsertAckResults{err}
	mmSendUpsertAck.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendUpsertAck.mock
}

// Set uses given function f to mock the Sender.SendUpsertAck method
func (mmSendUpsertAck *mSenderMockSendUpsertAck) Set(f func(ctx context.Context, msg *model.OutboundUpsert) (err error)) *SenderMock {
	if mmSendUpsertAck.defaultExpectation != nil {
		mmSendUpsertAck.mock.t.Fatalf("Default expectation is already set for the Sender.SendUpsertAck method")
	}

	if len(mmSendUpsertAck.expectations) > 0 {
		mmSendUpsertAck.mock.t.Fatalf("Some expectations are already set for the Sender.SendUpsertAck method")
	}

	mmSendUpsertAck.mock.funcSendUpsertAck = f
	mmSendUpsertAck.mock.funcSendUpsertAckOrigin = minimock.CallerInfo(1)
	return mmSendUpsertAck.mock
}

// When sets expectation for the Sender.SendUpsertAck which will trigger the result defined by the following
// Then helper
func (mmSendUpsertAck *mSenderMockSendUpsertAck) When(ctx context.Context, msg *model.OutboundUpsert) *SenderMockSendUpsertAckExpectation {
	if mmSendUpsertAck.mock.funcSendUpsertAck != nil {
		mmSendUpsertAck.mock.t.Fatalf("SenderMock.SendUpsertAck mock is already set by Set")
	}

	expectation := &SenderMockSendUpsertAckExpectation{
		mock:               mmSendUpsertAck.mock,
		params:             &SenderMockSendUpsertAckParams{ctx, msg},
		expectationOrigins: SenderMockSendUpsertAckExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendUpsertAck.expectations = append(mmSendUpsertAck.expectations, expectation)
	return expectation
}

// Then sets up Sender.SendUpsertAck return parameters for the expectation previously defined by the When method
func (e *SenderMockSendUpsertAckExpectation) Then(err error) *SenderMock {
	e.results = &SenderMockSendUpsertAckResults{err}
	return e.mock
}

// Times sets number of times Sender.SendUpsertAck should be invoked
func (mmSendUpsertAck *mSenderMockSendUpsertAck) Times(n uint64) *mSenderMockSendUpsertAck {
	if n == 0 {
		mmSendUpsertAck.mock.t.Fatalf("Times of SenderMock.SendUpsertAck mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendUpsertAck.expectedInvocations, n)
	mmSendUpsertAck.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendUpsertAck
}

func (mmSendUpsertAck *mSenderMockSendUpsertAck) invocationsDone() bool {
	if len(mmSendUpsertAck.expectations) == 0 && mmSendUpsertAck.defaultExpectation == nil && mmSendUpsertAck.mock.funcSendUpsertAck == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendUpsertAck.mock.afterSendUpsertAckCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendUpsertAck.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendUpsertAck implements mm_service.Sender
func (mmSendUpsertAck *SenderMock) SendUpsertAck(ctx context.Context, msg *model.OutboundUpsert) (err error) {
	mm_atomic.AddUint64(&mmSendUpsertAck.beforeSendUpsertAckCounter, 1)
	defer mm_atomic.AddUint64(&mmSendUpsertAck.afterSendUpsertAckCounter, 1)

	mmSendUpsertAck.t.Helper()

	if mmSendUpsertAck.inspectFuncSendUpsertAck != nil {
		mmSendUpsertAck.inspectFuncSendUpsertAck(ctx, msg)
	}

	mm_params := SenderMockSendUpsertAckParams{ctx, msg}

	// Record call args
	mmSendUpsertAck.SendUpsertAckMock.mutex.Lock()
	mmSendUpsertAck.SendUpsertAckMock.callArgs = append(mmSendUpsertAck.SendUpsertAckMock.callArgs, &mm_params)
	mmSendUpsertAck.SendUpsertAckMock.mutex.Unlock()

	for _, e := range mmSendUpsertAck.SendUpsertAckMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendUpsertAck.SendUpsertAckMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendUpsertAck.SendUpsertAckMock.defaultExpectation.Counter, 1)
		mm_want := mmSendUpsertAck.SendUpsertAckMock.defaultExpectation.params
		mm_want_ptrs := mmSendUpsertAck.SendUpsertAckMock.defaultExpectation.paramPtrs

		mm_got := SenderMockSendUpsertAckParams{ctx, msg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendUpsertAck.t.Errorf("SenderMock.SendUpsertAck got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendUpsertAck.SendUpsertAckMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmSendUpsertAck.t.Errorf("SenderMock.SendUpsertAck got unexpected parameter msg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendUpsertAck.SendUpsertAckMock.defaultExpectation.expectationOrigins.originMsg, *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendUpsertAck.t.Errorf("SenderMock.SendUpsertAck got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendUpsertAck.SendUpsertAckMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendUpsertAck.SendUpsertAckMock.defaultExpectation.results
		if mm_results == nil {
			mmSendUpsertAck.t.Fatal("No results are set for the SenderMock.SendUpsertAck")
		}
		return (*mm_results).err
	}
	if mmSendUpsertAck.funcSendUpsertAck != nil {
		return mmSendUpsertAck.funcSendUpsertAck(ctx, msg)
	}
	mmSendUpsertAck.t.Fatalf("Unexpected call to SenderMock.SendUpsertAck. %v %v", ctx, msg)
	return
}

// SendUpsertAckAfterCounter returns a count of finished SenderMock.SendUpsertAck invocations
func (mmSendUpsertAck *SenderMock) SendUpsertAckAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendUpsertAck.afterSendUpsertAckCounter)
}

// SendUpsertAckBeforeCounter returns a count of SenderMock.SendUpsertAck invocations
func (mmSendUpsertAck *SenderMock) SendUpsertAckBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendUpsertAck.beforeSendUpsertAckCounter)
}

// Calls returns a list of arguments used in each call to SenderMock.SendUpsertAck.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendUpsertAck *mSenderMockSendUpsertAck) Calls() []*SenderMockSendUpsertAckParams {
	mmSendUpsertAck.mutex.RLock()

	argCopy := make([]*SenderMockSendUpsertAckParams, len(mmSendUpsertAck.callArgs))
	copy(argCopy, mmSendUpsertAck.callArgs)

	mmSendUpsertAck.mutex.RUnlock()

	return argCopy
}

// MinimockSendUpsertAckDone returns true if the count of the SendUpsertAck invocations corresponds
// the number of defined expectations
func (m *SenderMock) MinimockSendUpsertAckDone() bool {
	if m.SendUpsertAckMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendUpsertAckMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendUpsertAckMock.invocationsDone()
}

// MinimockSendUpsertAckInspect logs each unmet expectation
func (m *SenderMock) MinimockSendUpsertAckInspect() {
	for _, e := range m.SendUpsertAckMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SenderMock.SendUpsertAck at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendUpsertAckCounter := mm_atomic.LoadUint64(&m.afterSendUpsertAckCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendUpsertAckMock.defaultExpectation != nil && afterSendUpsertAckCounter < 1 {
		if m.SendUpsertAckMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SenderMock.SendUpsertAck at\n%s", m.SendUpsertAckMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SenderMock.SendUpsertAck at\n%s with params: %#v", m.SendUpsertAckMock.defaultExpectation.expectationOrigins.origin, *m.SendUpsertAckMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendUpsertAck != nil && afterSendUpsertAckCounter < 1 {
		m.t.Errorf("Expected call to SenderMock.SendUpsertAck at\n%s", m.funcSendUpsertAckOrigin)
	}

	if !m.SendUpsertAckMock.invocationsDone() && afterSendUpsertAckCounter > 0 {
		m.t.Errorf("Expected %d calls to SenderMock.SendUpsertAck at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendUpsertAckMock.expectedInvocations), m.SendUpsertAckMock.expectedInvocationsOrigin, afterSendUpsertAckCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SenderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendErrorInspect()

			m.MinimockSendRemoveAckInspect()

			m.MinimockSendStatsInspect()

			m.MinimockSendUpsertAckInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendErrorDone() &&
		m.MinimockSendRemoveAckDone() &&
		m.MinimockSendStatsDone() &&
		m.MinimockSendUpsertAckDone()
}
