// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"agent/internal/model"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// XrayDriverMock implements mm_service.XrayDriver
type XrayDriverMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddUser          func(ctx context.Context, userID string) (err error)
	funcAddUserOrigin    string
	inspectFuncAddUser   func(ctx context.Context, userID string)
	afterAddUserCounter  uint64
	beforeAddUserCounter uint64
	AddUserMock          mXrayDriverMockAddUser

	funcBuildCreds          func(userID string) (s1 string, err error)
	funcBuildCredsOrigin    string
	inspectFuncBuildCreds   func(userID string)
	afterBuildCredsCounter  uint64
	beforeBuildCredsCounter uint64
	BuildCredsMock          mXrayDriverMockBuildCreds

	funcCollectStats          func(ctx context.Context) (upa1 []*model.UserUsage, err error)
	funcCollectStatsOrigin    string
	inspectFuncCollectStats   func(ctx context.Context)
	afterCollectStatsCounter  uint64
	beforeCollectStatsCounter uint64
	CollectStatsMock          mXrayDriverMockCollectStats

	funcListUsers          func(ctx context.Context) (sa1 []string, err error)
	funcListUsersOrigin    string
	inspectFuncListUsers   func(ctx context.Context)
	afterListUsersCounter  uint64
	beforeListUsersCounter uint64
	ListUsersMock          mXrayDriverMockListUsers

	funcRemoveUser          func(ctx context.Context, userID string) (err error)
	funcRemoveUserOrigin    string
	inspectFuncRemoveUser   func(ctx context.Context, userID string)
	afterRemoveUserCounter  uint64
	beforeRemoveUserCounter uint64
	RemoveUserMock          mXrayDriverMockRemoveUser
}

// NewXrayDriverMock returns a mock for mm_service.XrayDriver
func NewXrayDriverMock(t minimock.Tester) *XrayDriverMock {
	m := &XrayDriverMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddUserMock = mXrayDriverMockAddUser{mock: m}
	m.AddUserMock.callArgs = []*XrayDriverMockAddUserParams{}

	m.BuildCredsMock = mXrayDriverMockBuildCreds{mock: m}
	m.BuildCredsMock.callArgs = []*XrayDriverMockBuildCredsParams{}

	m.CollectStatsMock = mXrayDriverMockCollectStats{mock: m}
	m.CollectStatsMock.callArgs = []*XrayDriverMockCollectStatsParams{}

	m.ListUsersMock = mXrayDriverMockListUsers{mock: m}
	m.ListUsersMock.callArgs = []*XrayDriverMockListUsersParams{}

	m.RemoveUserMock = mXrayDriverMockRemoveUser{mock: m}
	m.RemoveUserMock.callArgs = []*XrayDriverMockRemoveUserParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mXrayDriverMockAddUser struct {
	optional           bool
	mock               *XrayDriverMock
	defaultExpectation *XrayDriverMockAddUserExpectation
	expectations       []*XrayDriverMockAddUserExpectation

	callArgs []*XrayDriverMockAddUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// XrayDriverMockAddUserExpectation specifies expectation struct of the XrayDriver.AddUser
type XrayDriverMockAddUserExpectation struct {
	mock               *XrayDriverMock
	params             *XrayDriverMockAddUserParams
	paramPtrs          *XrayDriverMockAddUserParamPtrs
	expectationOrigins XrayDriverMockAddUserExpectationOrigins
	results            *XrayDriverMockAddUserResults
	returnOrigin       string
	Counter            uint64
}

// XrayDriverMockAddUserParams contains parameters of the XrayDriver.AddUser
type XrayDriverMockAddUserParams struct {
	ctx    context.Context
	userID string
}

// XrayDriverMockAddUserParamPtrs contains pointers to parameters of the XrayDriver.AddUser
type XrayDriverMockAddUserParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// XrayDriverMockAddUserResults contains results of the XrayDriver.AddUser
type XrayDriverMockAddUserResults struct {
	err error
}

// XrayDriverMockAddUserOrigins contains origins of expectations of the XrayDriver.AddUser
type XrayDriverMockAddUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddUser *mXrayDriverMockAddUser) Optional() *mXrayDriverMockAddUser {
	mmAddUser.optional = true
	return mmAddUser
}

// Expect sets up expected params for XrayDriver.AddUser
func (mmAddUser *mXrayDriverMockAddUser) Expect(ctx context.Context, userID string) *mXrayDriverMockAddUser {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &XrayDriverMockAddUserExpectation{}
	}

	if mmAddUser.defaultExpectation.paramPtrs != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by ExpectParams functions")
	}

	mmAddUser.defaultExpectation.params = &XrayDriverMockAddUserParams{ctx, userID}
	mmAddUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddUser.expectations {
		if minimock.Equal(e.params, mmAddUser.defaultExpectation.params) {
			mmAddUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddUser.defaultExpectation.params)
		}
	}

	return mmAddUser
}

// ExpectCtxParam1 sets up expected param ctx for XrayDriver.AddUser
func (mmAddUser *mXrayDriverMockAddUser) ExpectCtxParam1(ctx context.Context) *mXrayDriverMockAddUser {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &XrayDriverMockAddUserExpectation{}
	}

	if mmAddUser.defaultExpectation.params != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by Expect")
	}

	if mmAddUser.defaultExpectation.paramPtrs == nil {
		mmAddUser.defaultExpectation.paramPtrs = &XrayDriverMockAddUserParamPtrs{}
	}
	mmAddUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmAddUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAddUser
}

// ExpectUserIDParam2 sets up expected param userID for XrayDriver.AddUser
func (mmAddUser *mXrayDriverMockAddUser) ExpectUserIDParam2(userID string) *mXrayDriverMockAddUser {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &XrayDriverMockAddUserExpectation{}
	}

	if mmAddUser.defaultExpectation.params != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by Expect")
	}

	if mmAddUser.defaultExpectation.paramPtrs == nil {
		mmAddUser.defaultExpectation.paramPtrs = &XrayDriverMockAddUserParamPtrs{}
	}
	mmAddUser.defaultExpectation.paramPtrs.userID = &userID
	mmAddUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmAddUser
}

// Inspect accepts an inspector function that has same arguments as the XrayDriver.AddUser
func (mmAddUser *mXrayDriverMockAddUser) Inspect(f func(ctx context.Context, userID string)) *mXrayDriverMockAddUser {
	if mmAddUser.mock.inspectFuncAddUser != nil {
		mmAddUser.mock.t.Fatalf("Inspect function is already set for XrayDriverMock.AddUser")
	}

	mmAddUser.mock.inspectFuncAddUser = f

	return mmAddUser
}

// Return sets up results that will be returned by XrayDriver.AddUser
func (mmAddUser *mXrayDriverMockAddUser) Return(err error) *XrayDriverMock {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by Set")
	}

	if mmAddUser.defaultExpectation == nil {
		mmAddUser.defaultExpectation = &XrayDriverMockAddUserExpectation{mock: mmAddUser.mock}
	}
	mmAddUser.defaultExpectation.results = &XrayDriverMockAddUserResults{err}
	mmAddUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddUser.mock
}

// Set uses given function f to mock the XrayDriver.AddUser method
func (mmAddUser *mXrayDriverMockAddUser) Set(f func(ctx context.Context, userID string) (err error)) *XrayDriverMock {
	if mmAddUser.defaultExpectation != nil {
		mmAddUser.mock.t.Fatalf("Default expectation is already set for the XrayDriver.AddUser method")
	}

	if len(mmAddUser.expectations) > 0 {
		mmAddUser.mock.t.Fatalf("Some expectations are already set for the XrayDriver.AddUser method")
	}

	mmAddUser.mock.funcAddUser = f
	mmAddUser.mock.funcAddUserOrigin = minimock.CallerInfo(1)
	return mmAddUser.mock
}

// When sets expectation for the XrayDriver.AddUser which will trigger the result defined by the following
// Then helper
func (mmAddUser *mXrayDriverMockAddUser) When(ctx context.Context, userID string) *XrayDriverMockAddUserExpectation {
	if mmAddUser.mock.funcAddUser != nil {
		mmAddUser.mock.t.Fatalf("XrayDriverMock.AddUser mock is already set by Set")
	}

	expectation := &XrayDriverMockAddUserExpectation{
		mock:               mmAddUser.mock,
		params:             &XrayDriverMockAddUserParams{ctx, userID},
		expectationOrigins: XrayDriverMockAddUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddUser.expectations = append(mmAddUser.expectations, expectation)
	return expectation
}

// Then sets up XrayDriver.AddUser return parameters for the expectation previously defined by the When method
func (e *XrayDriverMockAddUserExpectation) Then(err error) *XrayDriverMock {
	e.results = &XrayDriverMockAddUserResults{err}
	return e.mock
}

// Times sets number of times XrayDriver.AddUser should be invoked
func (mmAddUser *mXrayDriverMockAddUser) Times(n uint64) *mXrayDriverMockAddUser {
	if n == 0 {
		mmAddUser.mock.t.Fatalf("Times of XrayDriverMock.AddUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddUser.expectedInvocations, n)
	mmAddUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddUser
}

func (mmAddUser *mXrayDriverMockAddUser) invocationsDone() bool {
	if len(mmAddUser.expectations) == 0 && mmAddUser.defaultExpectation == nil && mmAddUser.mock.funcAddUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddUser.mock.afterAddUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddUser implements mm_service.XrayDriver
func (mmAddUser *XrayDriverMock) AddUser(ctx context.Context, userID string) (err error) {
	mm_atomic.AddUint64(&mmAddUser.beforeAddUserCounter, 1)
	defer mm_atomic.AddUint64(&mmAddUser.afterAddUserCounter, 1)

	mmAddUser.t.Helper()

	if mmAddUser.inspectFuncAddUser != nil {
		mmAddUser.inspectFuncAddUser(ctx, userID)
	}

	mm_params := XrayDriverMockAddUserParams{ctx, userID}

	// Record call args
	mmAddUser.AddUserMock.mutex.Lock()
	mmAddUser.AddUserMock.callArgs = append(mmAddUser.AddUserMock.callArgs, &mm_params)
	mmAddUser.AddUserMock.mutex.Unlock()

	for _, e := range mmAddUser.AddUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddUser.AddUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddUser.AddUserMock.defaultExpectation.Counter, 1)
		mm_want := mmAddUser.AddUserMock.defaultExpectation.params
		mm_want_ptrs := mmAddUser.AddUserMock.defaultExpectation.paramPtrs

		mm_got := XrayDriverMockAddUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAddUser.t.Errorf("XrayDriverMock.AddUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddUser.AddUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmAddUser.t.Errorf("XrayDriverMock.AddUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddUser.AddUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddUser.t.Errorf("XrayDriverMock.AddUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddUser.AddUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddUser.AddUserMock.defaultExpectation.results
		if mm_results == nil {
			mmAddUser.t.Fatal("No results are set for the XrayDriverMock.AddUser")
		}
		return (*mm_results).err
	}
	if mmAddUser.funcAddUser != nil {
		return mmAddUser.funcAddUser(ctx, userID)
	}
	mmAddUser.t.Fatalf("Unexpected call to XrayDriverMock.AddUser. %v %v", ctx, userID)
	return
}

// AddUserAfterCounter returns a count of finished XrayDriverMock.AddUser invocations
func (mmAddUser *XrayDriverMock) AddUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddUser.afterAddUserCounter)
}

// AddUserBeforeCounter returns a count of XrayDriverMock.AddUser invocations
func (mmAddUser *XrayDriverMock) AddUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddUser.beforeAddUserCounter)
}

// Calls returns a list of arguments used in each call to XrayDriverMock.AddUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddUser *mXrayDriverMockAddUser) Calls() []*XrayDriverMockAddUserParams {
	mmAddUser.mutex.RLock()

	argCopy := make([]*XrayDriverMockAddUserParams, len(mmAddUser.callArgs))
	copy(argCopy, mmAddUser.callArgs)

	mmAddUser.mutex.RUnlock()

	return argCopy
}

// MinimockAddUserDone returns true if the count of the AddUser invocations corresponds
// the number of defined expectations
func (m *XrayDriverMock) MinimockAddUserDone() bool {
	if m.AddUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddUserMock.invocationsDone()
}

// MinimockAddUserInspect logs each unmet expectation
func (m *XrayDriverMock) MinimockAddUserInspect() {
	for _, e := range m.AddUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to XrayDriverMock.AddUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddUserCounter := mm_atomic.LoadUint64(&m.afterAddUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddUserMock.defaultExpectation != nil && afterAddUserCounter < 1 {
		if m.AddUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to XrayDriverMock.AddUser at\n%s", m.AddUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to XrayDriverMock.AddUser at\n%s with params: %#v", m.AddUserMock.defaultExpectation.expectationOrigins.origin, *m.AddUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddUser != nil && afterAddUserCounter < 1 {
		m.t.Errorf("Expected call to XrayDriverMock.AddUser at\n%s", m.funcAddUserOrigin)
	}

	if !m.AddUserMock.invocationsDone() && afterAddUserCounter > 0 {
		m.t.Errorf("Expected %d calls to XrayDriverMock.AddUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddUserMock.expectedInvocations), m.AddUserMock.expectedInvocationsOrigin, afterAddUserCounter)
	}
}

type mXrayDriverMockBuildCreds struct {
	optional           bool
	mock               *XrayDriverMock
	defaultExpectation *XrayDriverMockBuildCredsExpectation
	expectations       []*XrayDriverMockBuildCredsExpectation

	callArgs []*XrayDriverMockBuildCredsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// XrayDriverMockBuildCredsExpectation specifies expectation struct of the XrayDriver.BuildCreds
type XrayDriverMockBuildCredsExpectation struct {
	mock               *XrayDriverMock
	params             *XrayDriverMockBuildCredsParams
	paramPtrs          *XrayDriverMockBuildCredsParamPtrs
	expectationOrigins XrayDriverMockBuildCredsExpectationOrigins
	results            *XrayDriverMockBuildCredsResults
	returnOrigin       string
	Counter            uint64
}

// XrayDriverMockBuildCredsParams contains parameters of the XrayDriver.BuildCreds
type XrayDriverMockBuildCredsParams struct {
	userID string
}

// XrayDriverMockBuildCredsParamPtrs contains pointers to parameters of the XrayDriver.BuildCreds
type XrayDriverMockBuildCredsParamPtrs struct {
	userID *string
}

// XrayDriverMockBuildCredsResults contains results of the XrayDriver.BuildCreds
type XrayDriverMockBuildCredsResults struct {
	s1  string
	err error
}

// XrayDriverMockBuildCredsOrigins contains origins of expectations of the XrayDriver.BuildCreds
type XrayDriverMockBuildCredsExpectationOrigins struct {
	origin       string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmBuildCreds *mXrayDriverMockBuildCreds) Optional() *mXrayDriverMockBuildCreds {
	mmBuildCreds.optional = true
	return mmBuildCreds
}

// Expect sets up expected params for XrayDriver.BuildCreds
func (mmBuildCreds *mXrayDriverMockBuildCreds) Expect(userID string) *mXrayDriverMockBuildCreds {
	if mmBuildCreds.mock.funcBuildCreds != nil {
		mmBuildCreds.mock.t.Fatalf("XrayDriverMock.BuildCreds mock is already set by Set")
	}

	if mmBuildCreds.defaultExpectation == nil {
		mmBuildCreds.defaultExpectation = &XrayDriverMockBuildCredsExpectation{}
	}

	if mmBuildCreds.defaultExpectation.paramPtrs != nil {
		mmBuildCreds.mock.t.Fatalf("XrayDriverMock.BuildCreds mock is already set by ExpectParams functions")
	}

	mmBuildCreds.defaultExpectation.params = &XrayDriverMockBuildCredsParams{userID}
	mmBuildCreds.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmBuildCreds.expectations {
		if minimock.Equal(e.params, mmBuildCreds.defaultExpectation.params) {
			mmBuildCreds.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmBuildCreds.defaultExpectation.params)
		}
	}

	return mmBuildCreds
}

// ExpectUserIDParam1 sets up expected param userID for XrayDriver.BuildCreds
func (mmBuildCreds *mXrayDriverMockBuildCreds) ExpectUserIDParam1(userID string) *mXrayDriverMockBuildCreds {
	if mmBuildCreds.mock.funcBuildCreds != nil {
		mmBuildCreds.mock.t.Fatalf("XrayDriverMock.BuildCreds mock is already set by Set")
	}

	if mmBuildCreds.defaultExpectation == nil {
		mmBuildCreds.defaultExpectation = &XrayDriverMockBuildCredsExpectation{}
	}

	if mmBuildCreds.defaultExpectation.params != nil {
		mmBuildCreds.mock.t.Fatalf("XrayDriverMock.BuildCreds mock is already set by Expect")
	}

	if mmBuildCreds.defaultExpectation.paramPtrs == nil {
		mmBuildCreds.defaultExpectation.paramPtrs = &XrayDriverMockBuildCredsParamPtrs{}
	}
	mmBuildCreds.defaultExpectation.paramPtrs.userID = &userID
	mmBuildCreds.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmBuildCreds
}

// Inspect accepts an inspector function that has same arguments as the XrayDriver.BuildCreds
func (mmBuildCreds *mXrayDriverMockBuildCreds) Inspect(f func(userID string)) *mXrayDriverMockBuildCreds {
	if mmBuildCreds.mock.inspectFuncBuildCreds != nil {
		mmBuildCreds.mock.t.Fatalf("Inspect function is already set for XrayDriverMock.BuildCreds")
	}

	mmBuildCreds.mock.inspectFuncBuildCreds = f

	return mmBuildCreds
}

// Return sets up results that will be returned by XrayDriver.BuildCreds
func (mmBuildCreds *mXrayDriverMockBuildCreds) Return(s1 string, err error) *XrayDriverMock {
	if mmBuildCreds.mock.funcBuildCreds != nil {
		mmBuildCreds.mock.t.Fatalf("XrayDriverMock.BuildCreds mock is already set by Set")
	}

	if mmBuildCreds.defaultExpectation == nil {
		mmBuildCreds.defaultExpectation = &XrayDriverMockBuildCredsExpectation{mock: mmBuildCreds.mock}
	}
	mmBuildCreds.defaultExpectation.results = &XrayDriverMockBuildCredsResults{s1, err}
	mmBuildCreds.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmBuildCreds.mock
}

// Set uses given function f to mock the XrayDriver.BuildCreds method
func (mmBuildCreds *mXrayDriverMockBuildCreds) Set(f func(userID string) (s1 string, err error)) *XrayDriverMock {
	if mmBuildCreds.defaultExpectation != nil {
		mmBuildCreds.mock.t.Fatalf("Default expectation is already set for the XrayDriver.BuildCreds method")
	}

	if len(mmBuildCreds.expectations) > 0 {
		mmBuildCreds.mock.t.Fatalf("Some expectations are already set for the XrayDriver.BuildCreds method")
	}

	mmBuildCreds.mock.funcBuildCreds = f
	mmBuildCreds.mock.funcBuildCredsOrigin = minimock.CallerInfo(1)
	return mmBuildCreds.mock
}

// When sets expectation for the XrayDriver.BuildCreds which will trigger the result defined by the following
// Then helper
func (mmBuildCreds *mXrayDriverMockBuildCreds) When(userID string) *XrayDriverMockBuildCredsExpectation {
	if mmBuildCreds.mock.funcBuildCreds != nil {
		mmBuildCreds.mock.t.Fatalf("XrayDriverMock.BuildCreds mock is already set by Set")
	}

	expectation := &XrayDriverMockBuildCredsExpectation{
		mock:               mmBuildCreds.mock,
		params:             &XrayDriverMockBuildCredsParams{userID},
		expectationOrigins: XrayDriverMockBuildCredsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmBuildCreds.expectations = append(mmBuildCreds.expectations, expectation)
	return expectation
}

// Then sets up XrayDriver.BuildCreds return parameters for the expectation previously defined by the When method
func (e *XrayDriverMockBuildCredsExpectation) Then(s1 string, err error) *XrayDriverMock {
	e.results = &XrayDriverMockBuildCredsResults{s1, err}
	return e.mock
}

// Times sets number of times XrayDriver.BuildCreds should be invoked
func (mmBuildCreds *mXrayDriverMockBuildCreds) Times(n uint64) *mXrayDriverMockBuildCreds {
	if n == 0 {
		mmBuildCreds.mock.t.Fatalf("Times of XrayDriverMock.BuildCreds mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmBuildCreds.expectedInvocations, n)
	mmBuildCreds.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmBuildCreds
}

func (mmBuildCreds *mXrayDriverMockBuildCreds) invocationsDone() bool {
	if len(mmBuildCreds.expectations) == 0 && mmBuildCreds.defaultExpectation == nil && mmBuildCreds.mock.funcBuildCreds == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmBuildCreds.mock.afterBuildCredsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmBuildCreds.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// BuildCreds implements mm_service.XrayDriver
func (mmBuildCreds *XrayDriverMock) BuildCreds(userID string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmBuildCreds.beforeBuildCredsCounter, 1)
	defer mm_atomic.AddUint64(&mmBuildCreds.afterBuildCredsCounter, 1)

	mmBuildCreds.t.Helper()

	if mmBuildCreds.inspectFuncBuildCreds != nil {
		mmBuildCreds.inspectFuncBuildCreds(userID)
	}

	mm_params := XrayDriverMockBuildCredsParams{userID}

	// Record call args
	mmBuildCreds.BuildCredsMock.mutex.Lock()
	mmBuildCreds.BuildCredsMock.callArgs = append(mmBuildCreds.BuildCredsMock.callArgs, &mm_params)
	mmBuildCreds.BuildCredsMock.mutex.Unlock()

	for _, e := range mmBuildCreds.BuildCredsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmBuildCreds.BuildCredsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmBuildCreds.BuildCredsMock.defaultExpectation.Counter, 1)
		mm_want := mmBuildCreds.BuildCredsMock.defaultExpectation.params
		mm_want_ptrs := mmBuildCreds.BuildCredsMock.defaultExpectation.paramPtrs

		mm_got := XrayDriverMockBuildCredsParams{userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmBuildCreds.t.Errorf("XrayDriverMock.BuildCreds got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmBuildCreds.BuildCredsMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmBuildCreds.t.Errorf("XrayDriverMock.BuildCreds got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmBuildCreds.BuildCredsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmBuildCreds.BuildCredsMock.defaultExpectation.results
		if mm_results == nil {
			mmBuildCreds.t.Fatal("No results are set for the XrayDriverMock.BuildCreds")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmBuildCreds.funcBuildCreds != nil {
		return mmBuildCreds.funcBuildCreds(userID)
	}
	mmBuildCreds.t.Fatalf("Unexpected call to XrayDriverMock.BuildCreds. %v", userID)
	return
}

// BuildCredsAfterCounter returns a count of finished XrayDriverMock.BuildCreds invocations
func (mmBuildCreds *XrayDriverMock) BuildCredsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBuildCreds.afterBuildCredsCounter)
}

// BuildCredsBeforeCounter returns a count of XrayDriverMock.BuildCreds invocations
func (mmBuildCreds *XrayDriverMock) BuildCredsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmBuildCreds.beforeBuildCredsCounter)
}

// Calls returns a list of arguments used in each call to XrayDriverMock.BuildCreds.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmBuildCreds *mXrayDriverMockBuildCreds) Calls() []*XrayDriverMockBuildCredsParams {
	mmBuildCreds.mutex.RLock()

	argCopy := make([]*XrayDriverMockBuildCredsParams, len(mmBuildCreds.callArgs))
	copy(argCopy, mmBuildCreds.callArgs)

	mmBuildCreds.mutex.RUnlock()

	return argCopy
}

// MinimockBuildCredsDone returns true if the count of the BuildCreds invocations corresponds
// the number of defined expectations
func (m *XrayDriverMock) MinimockBuildCredsDone() bool {
	if m.BuildCredsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.BuildCredsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.BuildCredsMock.invocationsDone()
}

// MinimockBuildCredsInspect logs each unmet expectation
func (m *XrayDriverMock) MinimockBuildCredsInspect() {
	for _, e := range m.BuildCredsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to XrayDriverMock.BuildCreds at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterBuildCredsCounter := mm_atomic.LoadUint64(&m.afterBuildCredsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.BuildCredsMock.defaultExpectation != nil && afterBuildCredsCounter < 1 {
		if m.BuildCredsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to XrayDriverMock.BuildCreds at\n%s", m.BuildCredsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to XrayDriverMock.BuildCreds at\n%s with params: %#v", m.BuildCredsMock.defaultExpectation.expectationOrigins.origin, *m.BuildCredsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcBuildCreds != nil && afterBuildCredsCounter < 1 {
		m.t.Errorf("Expected call to XrayDriverMock.BuildCreds at\n%s", m.funcBuildCredsOrigin)
	}

	if !m.BuildCredsMock.invocationsDone() && afterBuildCredsCounter > 0 {
		m.t.Errorf("Expected %d calls to XrayDriverMock.BuildCreds at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.BuildCredsMock.expectedInvocations), m.BuildCredsMock.expectedInvocationsOrigin, afterBuildCredsCounter)
	}
}

type mXrayDriverMockCollectStats struct {
	optional           bool
	mock               *XrayDriverMock
	defaultExpectation *XrayDriverMockCollectStatsExpectation
	expectations       []*XrayDriverMockCollectStatsExpectation

	callArgs []*XrayDriverMockCollectStatsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// XrayDriverMockCollectStatsExpectation specifies expectation struct of the XrayDriver.CollectStats
type XrayDriverMockCollectStatsExpectation struct {
	mock               *XrayDriverMock
	params             *XrayDriverMockCollectStatsParams
	paramPtrs          *XrayDriverMockCollectStatsParamPtrs
	expectationOrigins XrayDriverMockCollectStatsExpectationOrigins
	results            *XrayDriverMockCollectStatsResults
	returnOrigin       string
	Counter            uint64
}

// XrayDriverMockCollectStatsParams contains parameters of the XrayDriver.CollectStats
type XrayDriverMockCollectStatsParams struct {
	ctx context.Context
}

// XrayDriverMockCollectStatsParamPtrs contains pointers to parameters of the XrayDriver.CollectStats
type XrayDriverMockCollectStatsParamPtrs struct {
	ctx *context.Context
}

// XrayDriverMockCollectStatsResults contains results of the XrayDriver.CollectStats
type XrayDriverMockCollectStatsResults struct {
	upa1 []*model.UserUsage
	err  error
}

// XrayDriverMockCollectStatsOrigins contains origins of expectations of the XrayDriver.CollectStats
type XrayDriverMockCollectStatsExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCollectStats *mXrayDriverMockCollectStats) Optional() *mXrayDriverMockCollectStats {
	mmCollectStats.optional = true
	return mmCollectStats
}

// Expect sets up expected params for XrayDriver.CollectStats
func (mmCollectStats *mXrayDriverMockCollectStats) Expect(ctx context.Context) *mXrayDriverMockCollectStats {
	if mmCollectStats.mock.funcCollectStats != nil {
		mmCollectStats.mock.t.Fatalf("XrayDriverMock.CollectStats mock is already set by Set")
	}

	if mmCollectStats.defaultExpectation == nil {
		mmCollectStats.defaultExpectation = &XrayDriverMockCollectStatsExpectation{}
	}

	if mmCollectStats.defaultExpectation.paramPtrs != nil {
		mmCollectStats.mock.t.Fatalf("XrayDriverMock.CollectStats mock is already set by ExpectParams functions")
	}

	mmCollectStats.defaultExpectation.params = &XrayDriverMockCollectStatsParams{ctx}
	mmCollectStats.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCollectStats.expectations {
		if minimock.Equal(e.params, mmCollectStats.defaultExpectation.params) {
			mmCollectStats.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCollectStats.defaultExpectation.params)
		}
	}

	return mmCollectStats
}

// ExpectCtxParam1 sets up expected param ctx for XrayDriver.CollectStats
func (mmCollectStats *mXrayDriverMockCollectStats) ExpectCtxParam1(ctx context.Context) *mXrayDriverMockCollectStats {
	if mmCollectStats.mock.funcCollectStats != nil {
		mmCollectStats.mock.t.Fatalf("XrayDriverMock.CollectStats mock is already set by Set")
	}

	if mmCollectStats.defaultExpectation == nil {
		mmCollectStats.defaultExpectation = &XrayDriverMockCollectStatsExpectation{}
	}

	if mmCollectStats.defaultExpectation.params != nil {
		mmCollectStats.mock.t.Fatalf("XrayDriverMock.CollectStats mock is already set by Expect")
	}

	if mmCollectStats.defaultExpectation.paramPtrs == nil {
		mmCollectStats.defaultExpectation.paramPtrs = &XrayDriverMockCollectStatsParamPtrs{}
	}
	mmCollectStats.defaultExpectation.paramPtrs.ctx = &ctx
	mmCollectStats.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCollectStats
}

// Inspect accepts an inspector function that has same arguments as the XrayDriver.CollectStats
func (mmCollectStats *mXrayDriverMockCollectStats) Inspect(f func(ctx context.Context)) *mXrayDriverMockCollectStats {
	if mmCollectStats.mock.inspectFuncCollectStats != nil {
		mmCollectStats.mock.t.Fatalf("Inspect function is already set for XrayDriverMock.CollectStats")
	}

	mmCollectStats.mock.inspectFuncCollectStats = f

	return mmCollectStats
}

// Return sets up results that will be returned by XrayDriver.CollectStats
func (mmCollectStats *mXrayDriverMockCollectStats) Return(upa1 []*model.UserUsage, err error) *XrayDriverMock {
	if mmCollectStats.mock.funcCollectStats != nil {
		mmCollectStats.mock.t.Fatalf("XrayDriverMock.CollectStats mock is already set by Set")
	}

	if mmCollectStats.defaultExpectation == nil {
		mmCollectStats.defaultExpectation = &XrayDriverMockCollectStatsExpectation{mock: mmCollectStats.mock}
	}
	mmCollectStats.defaultExpectation.results = &XrayDriverMockCollectStatsResults{upa1, err}
	mmCollectStats.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCollectStats.mock
}

// Set uses given function f to mock the XrayDriver.CollectStats method
func (mmCollectStats *mXrayDriverMockCollectStats) Set(f func(ctx context.Context) (upa1 []*model.UserUsage, err error)) *XrayDriverMock {
	if mmCollectStats.defaultExpectation != nil {
		mmCollectStats.mock.t.Fatalf("Default expectation is already set for the XrayDriver.CollectStats method")
	}

	if len(mmCollectStats.expectations) > 0 {
		mmCollectStats.mock.t.Fatalf("Some expectations are already set for the XrayDriver.CollectStats method")
	}

	mmCollectStats.mock.funcCollectStats = f
	mmCollectStats.mock.funcCollectStatsOrigin = minimock.CallerInfo(1)
	return mmCollectStats.mock
}

// When sets expectation for the XrayDriver.CollectStats which will trigger the result defined by the following
// Then helper
func (mmCollectStats *mXrayDriverMockCollectStats) When(ctx context.Context) *XrayDriverMockCollectStatsExpectation {
	if mmCollectStats.mock.funcCollectStats != nil {
		mmCollectStats.mock.t.Fatalf("XrayDriverMock.CollectStats mock is already set by Set")
	}

	expectation := &XrayDriverMockCollectStatsExpectation{
		mock:               mmCollectStats.mock,
		params:             &XrayDriverMockCollectStatsParams{ctx},
		expectationOrigins: XrayDriverMockCollectStatsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCollectStats.expectations = append(mmCollectStats.expectations, expectation)
	return expectation
}

// Then sets up XrayDriver.CollectStats return parameters for the expectation previously defined by the When method
func (e *XrayDriverMockCollectStatsExpectation) Then(upa1 []*model.UserUsage, err error) *XrayDriverMock {
	e.results = &XrayDriverMockCollectStatsResults{upa1, err}
	return e.mock
}

// Times sets number of times XrayDriver.CollectStats should be invoked
func (mmCollectStats *mXrayDriverMockCollectStats) Times(n uint64) *mXrayDriverMockCollectStats {
	if n == 0 {
		mmCollectStats.mock.t.Fatalf("Times of XrayDriverMock.CollectStats mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCollectStats.expectedInvocations, n)
	mmCollectStats.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCollectStats
}

func (mmCollectStats *mXrayDriverMockCollectStats) invocationsDone() bool {
	if len(mmCollectStats.expectations) == 0 && mmCollectStats.defaultExpectation == nil && mmCollectStats.mock.funcCollectStats == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCollectStats.mock.afterCollectStatsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCollectStats.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CollectStats implements mm_service.XrayDriver
func (mmCollectStats *XrayDriverMock) CollectStats(ctx context.Context) (upa1 []*model.UserUsage, err error) {
	mm_atomic.AddUint64(&mmCollectStats.beforeCollectStatsCounter, 1)
	defer mm_atomic.AddUint64(&mmCollectStats.afterCollectStatsCounter, 1)

	mmCollectStats.t.Helper()

	if mmCollectStats.inspectFuncCollectStats != nil {
		mmCollectStats.inspectFuncCollectStats(ctx)
	}

	mm_params := XrayDriverMockCollectStatsParams{ctx}

	// Record call args
	mmCollectStats.CollectStatsMock.mutex.Lock()
	mmCollectStats.CollectStatsMock.callArgs = append(mmCollectStats.CollectStatsMock.callArgs, &mm_params)
	mmCollectStats.CollectStatsMock.mutex.Unlock()

	for _, e := range mmCollectStats.CollectStatsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.upa1, e.results.err
		}
	}

	if mmCollectStats.CollectStatsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCollectStats.CollectStatsMock.defaultExpectation.Counter, 1)
		mm_want := mmCollectStats.CollectStatsMock.defaultExpectation.params
		mm_want_ptrs := mmCollectStats.CollectStatsMock.defaultExpectation.paramPtrs

		mm_got := XrayDriverMockCollectStatsParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCollectStats.t.Errorf("XrayDriverMock.CollectStats got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCollectStats.CollectStatsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCollectStats.t.Errorf("XrayDriverMock.CollectStats got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCollectStats.CollectStatsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCollectStats.CollectStatsMock.defaultExpectation.results
		if mm_results == nil {
			mmCollectStats.t.Fatal("No results are set for the XrayDriverMock.CollectStats")
		}
		return (*mm_results).upa1, (*mm_results).err
	}
	if mmCollectStats.funcCollectStats != nil {
		return mmCollectStats.funcCollectStats(ctx)
	}
	mmCollectStats.t.Fatalf("Unexpected call to XrayDriverMock.CollectStats. %v", ctx)
	return
}

// CollectStatsAfterCounter returns a count of finished XrayDriverMock.CollectStats invocations
func (mmCollectStats *XrayDriverMock) CollectStatsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCollectStats.afterCollectStatsCounter)
}

// CollectStatsBeforeCounter returns a count of XrayDriverMock.CollectStats invocations
func (mmCollectStats *XrayDriverMock) CollectStatsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCollectStats.beforeCollectStatsCounter)
}

// Calls returns a list of arguments used in each call to XrayDriverMock.CollectStats.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCollectStats *mXrayDriverMockCollectStats) Calls() []*XrayDriverMockCollectStatsParams {
	mmCollectStats.mutex.RLock()

	argCopy := make([]*XrayDriverMockCollectStatsParams, len(mmCollectStats.callArgs))
	copy(argCopy, mmCollectStats.callArgs)

	mmCollectStats.mutex.RUnlock()

	return argCopy
}

// MinimockCollectStatsDone returns true if the count of the CollectStats invocations corresponds
// the number of defined expectations
func (m *XrayDriverMock) MinimockCollectStatsDone() bool {
	if m.CollectStatsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CollectStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CollectStatsMock.invocationsDone()
}

// MinimockCollectStatsInspect logs each unmet expectation
func (m *XrayDriverMock) MinimockCollectStatsInspect() {
	for _, e := range m.CollectStatsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to XrayDriverMock.CollectStats at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCollectStatsCounter := mm_atomic.LoadUint64(&m.afterCollectStatsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CollectStatsMock.defaultExpectation != nil && afterCollectStatsCounter < 1 {
		if m.CollectStatsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to XrayDriverMock.CollectStats at\n%s", m.CollectStatsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to XrayDriverMock.CollectStats at\n%s with params: %#v", m.CollectStatsMock.defaultExpectation.expectationOrigins.origin, *m.CollectStatsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCollectStats != nil && afterCollectStatsCounter < 1 {
		m.t.Errorf("Expected call to XrayDriverMock.CollectStats at\n%s", m.funcCollectStatsOrigin)
	}

	if !m.CollectStatsMock.invocationsDone() && afterCollectStatsCounter > 0 {
		m.t.Errorf("Expected %d calls to XrayDriverMock.CollectStats at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CollectStatsMock.expectedInvocations), m.CollectStatsMock.expectedInvocationsOrigin, afterCollectStatsCounter)
	}
}

type mXrayDriverMockListUsers struct {
	optional           bool
	mock               *XrayDriverMock
	defaultExpectation *XrayDriverMockListUsersExpectation
	expectations       []*XrayDriverMockListUsersExpectation

	callArgs []*XrayDriverMockListUsersParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// XrayDriverMockListUsersExpectation specifies expectation struct of the XrayDriver.ListUsers
type XrayDriverMockListUsersExpectation struct {
	mock               *XrayDriverMock
	params             *XrayDriverMockListUsersParams
	paramPtrs          *XrayDriverMockListUsersParamPtrs
	expectationOrigins XrayDriverMockListUsersExpectationOrigins
	results            *XrayDriverMockListUsersResults
	returnOrigin       string
	Counter            uint64
}

// XrayDriverMockListUsersParams contains parameters of the XrayDriver.ListUsers
type XrayDriverMockListUsersParams struct {
	ctx context.Context
}

// XrayDriverMockListUsersParamPtrs contains pointers to parameters of the XrayDriver.ListUsers
type XrayDriverMockListUsersParamPtrs struct {
	ctx *context.Context
}

// XrayDriverMockListUsersResults contains results of the XrayDriver.ListUsers
type XrayDriverMockListUsersResults struct {
	sa1 []string
	err error
}

// XrayDriverMockListUsersOrigins contains origins of expectations of the XrayDriver.ListUsers
type XrayDriverMockListUsersExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmListUsers *mXrayDriverMockListUsers) Optional() *mXrayDriverMockListUsers {
	mmListUsers.optional = true
	return mmListUsers
}

// Expect sets up expected params for XrayDriver.ListUsers
func (mmListUsers *mXrayDriverMockListUsers) Expect(ctx context.Context) *mXrayDriverMockListUsers {
	if mmListUsers.mock.funcListUsers != nil {
		mmListUsers.mock.t.Fatalf("XrayDriverMock.ListUsers mock is already set by Set")
	}

	if mmListUsers.defaultExpectation == nil {
		mmListUsers.defaultExpectation = &XrayDriverMockListUsersExpectation{}
	}

	if mmListUsers.defaultExpectation.paramPtrs != nil {
		mmListUsers.mock.t.Fatalf("XrayDriverMock.ListUsers mock is already set by ExpectParams functions")
	}

	mmListUsers.defaultExpectation.params = &XrayDriverMockListUsersParams{ctx}
	mmListUsers.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmListUsers.expectations {
		if minimock.Equal(e.params, mmListUsers.defaultExpectation.params) {
			mmListUsers.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmListUsers.defaultExpectation.params)
		}
	}

	return mmListUsers
}

// ExpectCtxParam1 sets up expected param ctx for XrayDriver.ListUsers
func (mmListUsers *mXrayDriverMockListUsers) ExpectCtxParam1(ctx context.Context) *mXrayDriverMockListUsers {
	if mmListUsers.mock.funcListUsers != nil {
		mmListUsers.mock.t.Fatalf("XrayDriverMock.ListUsers mock is already set by Set")
	}

	if mmListUsers.defaultExpectation == nil {
		mmListUsers.defaultExpectation = &XrayDriverMockListUsersExpectation{}
	}

	if mmListUsers.defaultExpectation.params != nil {
		mmListUsers.mock.t.Fatalf("XrayDriverMock.ListUsers mock is already set by Expect")
	}

	if mmListUsers.defaultExpectation.paramPtrs == nil {
		mmListUsers.defaultExpectation.paramPtrs = &XrayDriverMockListUsersParamPtrs{}
	}
	mmListUsers.defaultExpectation.paramPtrs.ctx = &ctx
	mmListUsers.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmListUsers
}

// Inspect accepts an inspector function that has same arguments as the XrayDriver.ListUsers
func (mmListUsers *mXrayDriverMockListUsers) Inspect(f func(ctx context.Context)) *mXrayDriverMockListUsers {
	if mmListUsers.mock.inspectFuncListUsers != nil {
		mmListUsers.mock.t.Fatalf("Inspect function is already set for XrayDriverMock.ListUsers")
	}

	mmListUsers.mock.inspectFuncListUsers = f

	return mmListUsers
}

// Return sets up results that will be returned by XrayDriver.ListUsers
func (mmListUsers *mXrayDriverMockListUsers) Return(sa1 []string, err error) *XrayDriverMock {
	if mmListUsers.mock.funcListUsers != nil {
		mmListUsers.mock.t.Fatalf("XrayDriverMock.ListUsers mock is already set by Set")
	}

	if mmListUsers.defaultExpectation == nil {
		mmListUsers.defaultExpectation = &XrayDriverMockListUsersExpectation{mock: mmListUsers.mock}
	}
	mmListUsers.defaultExpectation.results = &XrayDriverMockListUsersResults{sa1, err}
	mmListUsers.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmListUsers.mock
}

// Set uses given function f to mock the XrayDriver.ListUsers method
func (mmListUsers *mXrayDriverMockListUsers) Set(f func(ctx context.Context) (sa1 []string, err error)) *XrayDriverMock {
	if mmListUsers.defaultExpectation != nil {
		mmListUsers.mock.t.Fatalf("Default expectation is already set for the XrayDriver.ListUsers method")
	}

	if len(mmListUsers.expectations) > 0 {
		mmListUsers.mock.t.Fatalf("Some expectations are already set for the XrayDriver.ListUsers method")
	}

	mmListUsers.mock.funcListUsers = f
	mmListUsers.mock.funcListUsersOrigin = minimock.CallerInfo(1)
	return mmListUsers.mock
}

// When sets expectation for the XrayDriver.ListUsers which will trigger the result defined by the following
// Then helper
func (mmListUsers *mXrayDriverMockListUsers) When(ctx context.Context) *XrayDriverMockListUsersExpectation {
	if mmListUsers.mock.funcListUsers != nil {
		mmListUsers.mock.t.Fatalf("XrayDriverMock.ListUsers mock is already set by Set")
	}

	expectation := &XrayDriverMockListUsersExpectation{
		mock:               mmListUsers.mock,
		params:             &XrayDriverMockListUsersParams{ctx},
		expectationOrigins: XrayDriverMockListUsersExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmListUsers.expectations = append(mmListUsers.expectations, expectation)
	return expectation
}

// Then sets up XrayDriver.ListUsers return parameters for the expectation previously defined by the When method
func (e *XrayDriverMockListUsersExpectation) Then(sa1 []string, err error) *XrayDriverMock {
	e.results = &XrayDriverMockListUsersResults{sa1, err}
	return e.mock
}

// Times sets number of times XrayDriver.ListUsers should be invoked
func (mmListUsers *mXrayDriverMockListUsers) Times(n uint64) *mXrayDriverMockListUsers {
	if n == 0 {
		mmListUsers.mock.t.Fatalf("Times of XrayDriverMock.ListUsers mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmListUsers.expectedInvocations, n)
	mmListUsers.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmListUsers
}

func (mmListUsers *mXrayDriverMockListUsers) invocationsDone() bool {
	if len(mmListUsers.expectations) == 0 && mmListUsers.defaultExpectation == nil && mmListUsers.mock.funcListUsers == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmListUsers.mock.afterListUsersCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmListUsers.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ListUsers implements mm_service.XrayDriver
func (mmListUsers *XrayDriverMock) ListUsers(ctx context.Context) (sa1 []string, err error) {
	mm_atomic.AddUint64(&mmListUsers.beforeListUsersCounter, 1)
	defer mm_atomic.AddUint64(&mmListUsers.afterListUsersCounter, 1)

	mmListUsers.t.Helper()

	if mmListUsers.inspectFuncListUsers != nil {
		mmListUsers.inspectFuncListUsers(ctx)
	}

	mm_params := XrayDriverMockListUsersParams{ctx}

	// Record call args
	mmListUsers.ListUsersMock.mutex.Lock()
	mmListUsers.ListUsersMock.callArgs = append(mmListUsers.ListUsersMock.callArgs, &mm_params)
	mmListUsers.ListUsersMock.mutex.Unlock()

	for _, e := range mmListUsers.ListUsersMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmListUsers.ListUsersMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmListUsers.ListUsersMock.defaultExpectation.Counter, 1)
		mm_want := mmListUsers.ListUsersMock.defaultExpectation.params
		mm_want_ptrs := mmListUsers.ListUsersMock.defaultExpectation.paramPtrs

		mm_got := XrayDriverMockListUsersParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmListUsers.t.Errorf("XrayDriverMock.ListUsers got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmListUsers.ListUsersMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmListUsers.t.Errorf("XrayDriverMock.ListUsers got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmListUsers.ListUsersMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmListUsers.ListUsersMock.defaultExpectation.results
		if mm_results == nil {
			mmListUsers.t.Fatal("No results are set for the XrayDriverMock.ListUsers")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmListUsers.funcListUsers != nil {
		return mmListUsers.funcListUsers(ctx)
	}
	mmListUsers.t.Fatalf("Unexpected call to XrayDriverMock.ListUsers. %v", ctx)
	return
}

// ListUsersAfterCounter returns a count of finished XrayDriverMock.ListUsers invocations
func (mmListUsers *XrayDriverMock) ListUsersAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListUsers.afterListUsersCounter)
}

// ListUsersBeforeCounter returns a count of XrayDriverMock.ListUsers invocations
func (mmListUsers *XrayDriverMock) ListUsersBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmListUsers.beforeListUsersCounter)
}

// Calls returns a list of arguments used in each call to XrayDriverMock.ListUsers.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmListUsers *mXrayDriverMockListUsers) Calls() []*XrayDriverMockListUsersParams {
	mmListUsers.mutex.RLock()

	argCopy := make([]*XrayDriverMockListUsersParams, len(mmListUsers.callArgs))
	copy(argCopy, mmListUsers.callArgs)

	mmListUsers.mutex.RUnlock()

	return argCopy
}

// MinimockListUsersDone returns true if the count of the ListUsers invocations corresponds
// the number of defined expectations
func (m *XrayDriverMock) MinimockListUsersDone() bool {
	if m.ListUsersMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ListUsersMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ListUsersMock.invocationsDone()
}

// MinimockListUsersInspect logs each unmet expectation
func (m *XrayDriverMock) MinimockListUsersInspect() {
	for _, e := range m.ListUsersMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to XrayDriverMock.ListUsers at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterListUsersCounter := mm_atomic.LoadUint64(&m.afterListUsersCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ListUsersMock.defaultExpectation != nil && afterListUsersCounter < 1 {
		if m.ListUsersMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to XrayDriverMock.ListUsers at\n%s", m.ListUsersMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to XrayDriverMock.ListUsers at\n%s with params: %#v", m.ListUsersMock.defaultExpectation.expectationOrigins.origin, *m.ListUsersMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcListUsers != nil && afterListUsersCounter < 1 {
		m.t.Errorf("Expected call to XrayDriverMock.ListUsers at\n%s", m.funcListUsersOrigin)
	}

	if !m.ListUsersMock.invocationsDone() && afterListUsersCounter > 0 {
		m.t.Errorf("Expected %d calls to XrayDriverMock.ListUsers at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ListUsersMock.expectedInvocations), m.ListUsersMock.expectedInvocationsOrigin, afterListUsersCounter)
	}
}

type mXrayDriverMockRemoveUser struct {
	optional           bool
	mock               *XrayDriverMock
	defaultExpectation *XrayDriverMockRemoveUserExpectation
	expectations       []*XrayDriverMockRemoveUserExpectation

	callArgs []*XrayDriverMockRemoveUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// XrayDriverMockRemoveUserExpectation specifies expectation struct of the XrayDriver.RemoveUser
type XrayDriverMockRemoveUserExpectation struct {
	mock               *XrayDriverMock
	params             *XrayDriverMockRemoveUserParams
	paramPtrs          *XrayDriverMockRemoveUserParamPtrs
	expectationOrigins XrayDriverMockRemoveUserExpectationOrigins
	results            *XrayDriverMockRemoveUserResults
	returnOrigin       string
	Counter            uint64
}

// XrayDriverMockRemoveUserParams contains parameters of the XrayDriver.RemoveUser
type XrayDriverMockRemoveUserParams struct {
	ctx    context.Context
	userID string
}

// XrayDriverMockRemoveUserParamPtrs contains pointers to parameters of the XrayDriver.RemoveUser
type XrayDriverMockRemoveUserParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// XrayDriverMockRemoveUserResults contains results of the XrayDriver.RemoveUser
type XrayDriverMockRemoveUserResults struct {
	err error
}

// XrayDriverMockRemoveUserOrigins contains origins of expectations of the XrayDriver.RemoveUser
type XrayDriverMockRemoveUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRemoveUser *mXrayDriverMockRemoveUser) Optional() *mXrayDriverMockRemoveUser {
	mmRemoveUser.optional = true
	return mmRemoveUser
}

// Expect sets up expected params for XrayDriver.RemoveUser
func (mmRemoveUser *mXrayDriverMockRemoveUser) Expect(ctx context.Context, userID string) *mXrayDriverMockRemoveUser {
	if mmRemoveUser.mock.funcRemoveUser != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by Set")
	}

	if mmRemoveUser.defaultExpectation == nil {
		mmRemoveUser.defaultExpectation = &XrayDriverMockRemoveUserExpectation{}
	}

	if mmRemoveUser.defaultExpectation.paramPtrs != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by ExpectParams functions")
	}

	mmRemoveUser.defaultExpectation.params = &XrayDriverMockRemoveUserParams{ctx, userID}
	mmRemoveUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRemoveUser.expectations {
		if minimock.Equal(e.params, mmRemoveUser.defaultExpectation.params) {
			mmRemoveUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRemoveUser.defaultExpectation.params)
		}
	}

	return mmRemoveUser
}

// ExpectCtxParam1 sets up expected param ctx for XrayDriver.RemoveUser
func (mmRemoveUser *mXrayDriverMockRemoveUser) ExpectCtxParam1(ctx context.Context) *mXrayDriverMockRemoveUser {
	if mmRemoveUser.mock.funcRemoveUser != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by Set")
	}

	if mmRemoveUser.defaultExpectation == nil {
		mmRemoveUser.defaultExpectation = &XrayDriverMockRemoveUserExpectation{}
	}

	if mmRemoveUser.defaultExpectation.params != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by Expect")
	}

	if mmRemoveUser.defaultExpectation.paramPtrs == nil {
		mmRemoveUser.defaultExpectation.paramPtrs = &XrayDriverMockRemoveUserParamPtrs{}
	}
	mmRemoveUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmRemoveUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRemoveUser
}

// ExpectUserIDParam2 sets up expected param userID for XrayDriver.RemoveUser
func (mmRemoveUser *mXrayDriverMockRemoveUser) ExpectUserIDParam2(userID string) *mXrayDriverMockRemoveUser {
	if mmRemoveUser.mock.funcRemoveUser != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by Set")
	}

	if mmRemoveUser.defaultExpectation == nil {
		mmRemoveUser.defaultExpectation = &XrayDriverMockRemoveUserExpectation{}
	}

	if mmRemoveUser.defaultExpectation.params != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by Expect")
	}

	if mmRemoveUser.defaultExpectation.paramPtrs == nil {
		mmRemoveUser.defaultExpectation.paramPtrs = &XrayDriverMockRemoveUserParamPtrs{}
	}
	mmRemoveUser.defaultExpectation.paramPtrs.userID = &userID
	mmRemoveUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmRemoveUser
}

// Inspect accepts an inspector function that has same arguments as the XrayDriver.RemoveUser
func (mmRemoveUser *mXrayDriverMockRemoveUser) Inspect(f func(ctx context.Context, userID string)) *mXrayDriverMockRemoveUser {
	if mmRemoveUser.mock.inspectFuncRemoveUser != nil {
		mmRemoveUser.mock.t.Fatalf("Inspect function is already set for XrayDriverMock.RemoveUser")
	}

	mmRemoveUser.mock.inspectFuncRemoveUser = f

	return mmRemoveUser
}

// Return sets up results that will be returned by XrayDriver.RemoveUser
func (mmRemoveUser *mXrayDriverMockRemoveUser) Return(err error) *XrayDriverMock {
	if mmRemoveUser.mock.funcRemoveUser != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by Set")
	}

	if mmRemoveUser.defaultExpectation == nil {
		mmRemoveUser.defaultExpectation = &XrayDriverMockRemoveUserExpectation{mock: mmRemoveUser.mock}
	}
	mmRemoveUser.defaultExpectation.results = &XrayDriverMockRemoveUserResults{err}
	mmRemoveUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRemoveUser.mock
}

// Set uses given function f to mock the XrayDriver.RemoveUser method
func (mmRemoveUser *mXrayDriverMockRemoveUser) Set(f func(ctx context.Context, userID string) (err error)) *XrayDriverMock {
	if mmRemoveUser.defaultExpectation != nil {
		mmRemoveUser.mock.t.Fatalf("Default expectation is already set for the XrayDriver.RemoveUser method")
	}

	if len(mmRemoveUser.expectations) > 0 {
		mmRemoveUser.mock.t.Fatalf("Some expectations are already set for the XrayDriver.RemoveUser method")
	}

	mmRemoveUser.mock.funcRemoveUser = f
	mmRemoveUser.mock.funcRemoveUserOrigin = minimock.CallerInfo(1)
	return mmRemoveUser.mock
}

// When sets expectation for the XrayDriver.RemoveUser which will trigger the result defined by the following
// Then helper
func (mmRemoveUser *mXrayDriverMockRemoveUser) When(ctx context.Context, userID string) *XrayDriverMockRemoveUserExpectation {
	if mmRemoveUser.mock.funcRemoveUser != nil {
		mmRemoveUser.mock.t.Fatalf("XrayDriverMock.RemoveUser mock is already set by Set")
	}

	expectation := &XrayDriverMockRemoveUserExpectation{
		mock:               mmRemoveUser.mock,
		params:             &XrayDriverMockRemoveUserParams{ctx, userID},
		expectationOrigins: XrayDriverMockRemoveUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRemoveUser.expectations = append(mmRemoveUser.expectations, expectation)
	return expectation
}

// Then sets up XrayDriver.RemoveUser return parameters for the expectation previously defined by the When method
func (e *XrayDriverMockRemoveUserExpectation) Then(err error) *XrayDriverMock {
	e.results = &XrayDriverMockRemoveUserResults{err}
	return e.mock
}

// Times sets number of times XrayDriver.RemoveUser should be invoked
func (mmRemoveUser *mXrayDriverMockRemoveUser) Times(n uint64) *mXrayDriverMockRemoveUser {
	if n == 0 {
		mmRemoveUser.mock.t.Fatalf("Times of XrayDriverMock.RemoveUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRemoveUser.expectedInvocations, n)
	mmRemoveUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRemoveUser
}

func (mmRemoveUser *mXrayDriverMockRemoveUser) invocationsDone() bool {
	if len(mmRemoveUser.expectations) == 0 && mmRemoveUser.defaultExpectation == nil && mmRemoveUser.mock.funcRemoveUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRemoveUser.mock.afterRemoveUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRemoveUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RemoveUser implements mm_service.XrayDriver
func (mmRemoveUser *XrayDriverMock) RemoveUser(ctx context.Context, userID string) (err error) {
	mm_atomic.AddUint64(&mmRemoveUser.beforeRemoveUserCounter, 1)
	defer mm_atomic.AddUint64(&mmRemoveUser.afterRemoveUserCounter, 1)

	mmRemoveUser.t.Helper()

	if mmRemoveUser.inspectFuncRemoveUser != nil {
		mmRemoveUser.inspectFuncRemoveUser(ctx, userID)
	}

	mm_params := XrayDriverMockRemoveUserParams{ctx, userID}

	// Record call args
	mmRemoveUser.RemoveUserMock.mutex.Lock()
	mmRemoveUser.RemoveUserMock.callArgs = append(mmRemoveUser.RemoveUserMock.callArgs, &mm_params)
	mmRemoveUser.RemoveUserMock.mutex.Unlock()

	for _, e := range mmRemoveUser.RemoveUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRemoveUser.RemoveUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRemoveUser.RemoveUserMock.defaultExpectation.Counter, 1)
		mm_want := mmRemoveUser.RemoveUserMock.defaultExpectation.params
		mm_want_ptrs := mmRemoveUser.RemoveUserMock.defaultExpectation.paramPtrs

		mm_got := XrayDriverMockRemoveUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRemoveUser.t.Errorf("XrayDriverMock.RemoveUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRemoveUser.RemoveUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmRemoveUser.t.Errorf("XrayDriverMock.RemoveUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRemoveUser.RemoveUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRemoveUser.t.Errorf("XrayDriverMock.RemoveUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRemoveUser.RemoveUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRemoveUser.RemoveUserMock.defaultExpectation.results
		if mm_results == nil {
			mmRemoveUser.t.Fatal("No results are set for the XrayDriverMock.RemoveUser")
		}
		return (*mm_results).err
	}
	if mmRemoveUser.funcRemoveUser != nil {
		return mmRemoveUser.funcRemoveUser(ctx, userID)
	}
	mmRemoveUser.t.Fatalf("Unexpected call to XrayDriverMock.RemoveUser. %v %v", ctx, userID)
	return
}

// RemoveUserAfterCounter returns a count of finished XrayDriverMock.RemoveUser invocations
func (mmRemoveUser *XrayDriverMock) RemoveUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRemoveUser.afterRemoveUserCounter)
}

// RemoveUserBeforeCounter returns a count of XrayDriverMock.RemoveUser invocations
func (mmRemoveUser *XrayDriverMock) RemoveUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRemoveUser.beforeRemoveUserCounter)
}

// Calls returns a list of arguments used in each call to XrayDriverMock.RemoveUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRemoveUser *mXrayDriverMockRemoveUser) Calls() []*XrayDriverMockRemoveUserParams {
	mmRemoveUser.mutex.RLock()

	argCopy := make([]*XrayDriverMockRemoveUserParams, len(mmRemoveUser.callArgs))
	copy(argCopy, mmRemoveUser.callArgs)

	mmRemoveUser.mutex.RUnlock()

	return argCopy
}

// MinimockRemoveUserDone returns true if the count of the RemoveUser invocations corresponds
// the number of defined expectations
func (m *XrayDriverMock) MinimockRemoveUserDone() bool {
	if m.RemoveUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RemoveUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RemoveUserMock.invocationsDone()
}

// MinimockRemoveUserInspect logs each unmet expectation
func (m *XrayDriverMock) MinimockRemoveUserInspect() {
	for _, e := range m.RemoveUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to XrayDriverMock.RemoveUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRemoveUserCounter := mm_atomic.LoadUint64(&m.afterRemoveUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RemoveUserMock.defaultExpectation != nil && afterRemoveUserCounter < 1 {
		if m.RemoveUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to XrayDriverMock.RemoveUser at\n%s", m.RemoveUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to XrayDriverMock.RemoveUser at\n%s with params: %#v", m.RemoveUserMock.defaultExpectation.expectationOrigins.origin, *m.RemoveUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRemoveUser != nil && afterRemoveUserCounter < 1 {
		m.t.Errorf("Expected call to XrayDriverMock.RemoveUser at\n%s", m.funcRemoveUserOrigin)
	}

	if !m.RemoveUserMock.invocationsDone() && afterRemoveUserCounter > 0 {
		m.t.Errorf("Expected %d calls to XrayDriverMock.RemoveUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RemoveUserMock.expectedInvocations), m.RemoveUserMock.expectedInvocationsOrigin, afterRemoveUserCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *XrayDriverMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddUserInspect()

			m.MinimockBuildCredsInspect()

			m.MinimockCollectStatsInspect()

			m.MinimockListUsersInspect()

			m.MinimockRemoveUserInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *XrayDriverMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *XrayDriverMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddUserDone() &&
		m.MinimockBuildCredsDone() &&
		m.MinimockCollectStatsDone() &&
		m.MinimockListUsersDone() &&
		m.MinimockRemoveUserDone()
}
